#!/usr/bin/env python3
"""
Faber CMS Admin - API Client Generator

Generates TypeScript API client for the CMS Worker.
"""

from typing import Any, Dict


def generate_admin_api_client(config: Dict[str, Any]) -> Dict[str, str]:
    """Generate TypeScript API client and types."""
    project_name = config["project_name"]
    worker_url = config["worker_url"]

    files = {}

    # Types file
    files["types.ts"] = f"""// types.ts - CMS API Types
// Generated by faber-cms for {project_name}

// Health check response
export interface HealthResponse {{
  status: 'ok' | 'error'
  timestamp: string
  version?: string
}}

// Collections
export interface Collection {{
  id: string
  name: string
  display_name: string
  description?: string
  content_type_name: string
  schema?: Record<string, any>
  created_at: string
  updated_at: string
}}

export interface CollectionsResponse {{
  items: Collection[]
  total: number
  limit: number
  offset: number
}}

// Content Items
export interface ContentItem {{
  id: string
  collection: string
  data: Record<string, any>
  status: 'draft' | 'published' | 'archived'
  created_at: string
  updated_at: string
  published_at?: string
}}

export interface ContentResponse {{
  items: ContentItem[]
  total: number
  limit: number
  offset: number
}}

// API Response wrapper
export interface ApiResponse<T> {{
  success: boolean
  data?: T
  error?: {{
    message: string
    code?: string
  }}
}}

// Form data for content creation/update
export interface ContentFormData {{
  [key: string]: any
}}

// Collection creation/update
export interface CollectionFormData {{
  name: string
  display_name: string
  description?: string
  content_type_name: string
}}
"""

    # API Client file
    files["api-client.ts"] = f"""// api-client.ts - CMS Worker API Client
// Generated by faber-cms for {project_name}
import type {{ HealthResponse, Collection, CollectionsResponse, ContentItem, ContentResponse, ApiResponse, ContentFormData, CollectionFormData }} from './types';

const WORKER_URL = "{worker_url}";

/**
 * Generic API fetch handler
 */
async function fetcher<T>(input: RequestInfo, init?: RequestInit): Promise<ApiResponse<T>> {{
  try {{
    const response = await fetch(input, {{
      headers: {{
        'Content-Type': 'application/json',
        // Add auth headers if needed (e.g., Cloudflare Access JWT)
        // 'Authorization': `Bearer ${{getAccessToken()}}`
      }},
      ...init,
    }});
    
    if (!response.ok) {{
      const errorData = await response.json().catch(() => ({}));
      return {{
        success: false,
        error: {{
          message: errorData.message || `$${ {response.status} }`,
          code: `$${ {response.status} }`
        }}
      }};
    }}
    
    const data = await response.json();
    return {{
      success: true,
      data: data as T
    }};
  }} catch (err) {{
    return {{
      success: false,
      error: {{
        message: err instanceof Error ? err.message : 'Unknown error',
        code: 'NETWORK_ERROR'
      }}
    }};
  }}
}}

/**
 * Health check
 */
export async function getHealth(): Promise<ApiResponse<HealthResponse>> {{
  return fetcher<HealthResponse>(`${WORKER_URL}/api/health`);
}};

/**
 * Collections
 */
export async function getCollections(): Promise<ApiResponse<CollectionsResponse>> {{
  return fetcher<CollectionsResponse>(`${WORKER_URL}/api/collections`);
}};

export async function getCollection(id: string): Promise<ApiResponse<Collection>> {{
  return fetcher<Collection>(`${WORKER_URL}/api/collections/${{id}}`);
}};

export async function createCollection(data: CollectionFormData): Promise<ApiResponse<Collection>> {{
  return fetcher<Collection>(`${WORKER_URL}/api/collections`, {{
    method: 'POST',
    body: JSON.stringify(data),
  }});
}};

export async function updateCollection(id: string, data: Partial<CollectionFormData>): Promise<ApiResponse<Collection>> {{
  return fetcher<Collection>(`${WORKER_URL}/api/collections/${{id}}`, {{
    method: 'PUT',
    body: JSON.stringify(data),
  }});
}};

export async function deleteCollection(id: string): Promise<ApiResponse<void>> {{
  return fetcher<void>(`${WORKER_URL}/api/collections/${{id}}`, {{
    method: 'DELETE',
  }});
}};

/**
 * Content Items
 */
export async function getContent(params?: {{
  collection?: string
  limit?: number
  offset?: number
  status?: 'draft' | 'published' | 'archived'
  search?: string
}}): Promise<ApiResponse<ContentResponse>> {{
  const url = new URL(`${WORKER_URL}/api/content`);
  if (params) {{
    Object.entries(params).forEach(([key, value]) => {{
      if (value !== undefined && value !== null) {{
        url.searchParams.append(key, String(value));
      }}
    }});
  }}
  return fetcher<ContentResponse>(url.toString());
}};

export async function getContentItem(id: string): Promise<ApiResponse<ContentItem>> {{
  return fetcher<ContentItem>(`${WORKER_URL}/api/content/${{id}}`);
}};

export async function createContentItem(collection: string, data: ContentFormData): Promise<ApiResponse<ContentItem>> {{
  return fetcher<ContentItem>(`${WORKER_URL}/api/content`, {{
    method: 'POST',
    body: JSON.stringify({{ collection, ...data }}),
  }});
}};

export async function updateContentItem(id: string, data: Partial<ContentFormData>): Promise<ApiResponse<ContentItem>> {{
  return fetcher<ContentItem>(`${WORKER_URL}/api/content/${{id}}`, {{
    method: 'PUT',
    body: JSON.stringify(data),
  }});
}};

export async function deleteContentItem(id: string): Promise<ApiResponse<void>> {{
  return fetcher<void>(`${WORKER_URL}/api/content/${{id}}`, {{
    method: 'DELETE',
  }});
}};

/**
 * Utility: Get Cloudflare Access JWT (if applicable)
 */
// function getAccessToken(): string | null {{
//   // Implementation depends on how you store/retrieve the token
//   // This could be from localStorage, cookies, or a backend proxy
//   return localStorage.getItem('cf_access_token') || null;
// }}

/**
 * Convenience functions for common operations
 */
export const cmsApi = {{
  health: getHealth,
  collections: {{
    list: getCollections,
    get: getCollection,
    create: createCollection,
    update: updateCollection,
    delete: deleteCollection
  }},
  content: {{
    list: getContent,
    get: getContentItem,
    create: createContentItem,
    update: updateContentItem,
    delete: deleteContentItem
  }}
}};

export default cmsApi;
"""

    return files


if __name__ == "__main__":
    print("Use via generate_admin_ui.py")