#!/usr/bin/env python3
"""
Faber CMS Admin - Admin Pages Generator

Generates Astro pages for the admin UI.
"""

from typing import Any, Dict


def generate_admin_pages(config: Dict[str, Any]) -> Dict[str, str]:
    """Generate all admin pages."""
    project_name = config["project_name"]
    worker_url = config["worker_url"]

    pages = {}

    # Dashboard page
    pages["index.astro"] = f"""---
// Dashboard.astro - Admin Dashboard
// Generated by faber-cms for {project_name}

import BaseLayout from "@/layouts/BaseLayout.astro";
import Sidebar from "@/components/admin/Sidebar.astro";
import Header from "@/components/admin/Header.astro";
---

<BaseLayout title="Dashboard | CMS Admin" description="Content Management System Dashboard">
  <div class="flex h-screen bg-faber-background">
    <!-- Sidebar -->
    <Sidebar />

    <!-- Main Content -->
    <div class="flex-1 flex flex-col min-w-0">
      <Header title="Dashboard" subtitle="Overview of your content" />

      <main class="flex-1 p-6 md:p-8 overflow-auto">
        <!-- Stats Grid -->
        <section class="mb-8">
          <h2 class="text-xl font-semibold text-faber-text mb-4">Content Statistics</h2>
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4" id="stats-grid">
            <!-- Stats loaded via JS -->
            <div class="bg-faber-surface border border-faber-border rounded-xl p-6 animate-pulse">
              <div class="h-4 w-1/4 bg-faber-border rounded mb-2"></div>
              <div class="h-8 w-1/2 bg-faber-border rounded"></div>
            </div>
            <div class="bg-faber-surface border border-faber-border rounded-xl p-6 animate-pulse">
              <div class="h-4 w-1/4 bg-faber-border rounded mb-2"></div>
              <div class="h-8 w-1/2 bg-faber-border rounded"></div>
            </div>
            <div class="bg-faber-surface border border-faber-border rounded-xl p-6 animate-pulse">
              <div class="h-4 w-1/4 bg-faber-border rounded mb-2"></div>
              <div class="h-8 w-1/2 bg-faber-border rounded"></div>
            </div>
            <div class="bg-faber-surface border border-faber-border rounded-xl p-6 animate-pulse">
              <div class="h-4 w-1/4 bg-faber-border rounded mb-2"></div>
              <div class="h-8 w-1/2 bg-faber-border rounded"></div>
            </div>
          </div>
        </section>

        <!-- Quick Actions -->
        <section class="mb-8">
          <h2 class="text-xl font-semibold text-faber-text mb-4">Quick Actions</h2>
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <a href="/admin/content" class="bg-faber-surface border border-faber-border rounded-xl p-6 hover:border-faber-primary/50 transition-colors">
              <div class="text-3xl mb-2">📝</div>
              <h3 class="font-semibold text-faber-text">Manage Content</h3>
              <p class="text-faber-text-muted text-sm mt-1">View and edit all content collections</p>
            </a>
            <a href="/admin/settings" class="bg-faber-surface border border-faber-border rounded-xl p-6 hover:border-faber-primary/50 transition-colors">
              <div class="text-3xl mb-2">⚙️</div>
              <h3 class="font-semibold text-faber-text">Settings</h3>
              <p class="text-faber-text-muted text-sm mt-1">Configure collections and preferences</p>
            </a>
            <div class="bg-faber-surface border border-faber-border rounded-xl p-6">
              <div class="text-3xl mb-2">📊</div>
              <h3 class="font-semibold text-faber-text">Analytics</h3>
              <p class="text-faber-text-muted text-sm mt-1">View content performance (coming soon)</p>
            </div>
          </div>
        </section>

        <!-- Recent Content -->
        <section>
          <div class="flex items-center justify-between mb-4">
            <h2 class="text-xl font-semibold text-faber-text">Recent Content</h2>
            <a href="/admin/content" class="text-sm text-faber-primary hover:underline">View all →</a>
          </div>
          <div class="bg-faber-surface border border-faber-border rounded-xl overflow-hidden" id="recent-content">
            <div class="p-6 text-center text-faber-text-muted">Loading recent content...</div>
          </div>
        </section>
      </main>
    </div>
  </div>

  <script is:inline>
    const WORKER_URL = "{worker_url}";

    // Fetch and display stats
    async function loadStats() {{
      try {{
        const response = await fetch(`${{WORKER_URL}}/api/health`);
        if (response.ok) {{
          const data = await response.json();
          // Update stats when we have real data
        }}
      }} catch (e) {{
        console.warn('Could not load stats:', e);
      }}
    }}

    // Fetch recent content
    async function loadRecentContent() {{
      try {{
        const response = await fetch(`${{WORKER_URL}}/api/content?limit=5&status=published`);
        if (response.ok) {{
          const data = await response.json();
          renderRecentContent(data.items || []);
        }}
      }} catch (e) {{
        console.warn('Could not load recent content:', e);
        document.getElementById('recent-content').innerHTML = 
          '<div class="p-6 text-center text-faber-text-muted">Unable to load recent content</div>';
      }}
    }}

    function renderRecentContent(items) {{
      if (items.length === 0) {{
        document.getElementById('recent-content').innerHTML = 
          '<div class="p-6 text-center text-faber-text-muted">No content yet. <a href="/admin/content" class="text-faber-primary underline">Create your first item</a></div>';
        return;
      }}

      const html = `
        <table class="w-full">
          <thead>
            <tr class="border-b border-faber-border">
              <th class="text-left p-3 font-medium text-faber-text-muted text-sm">Title</th>
              <th class="text-left p-3 font-medium text-faber-text-muted text-sm">Collection</th>
              <th class="text-left p-3 font-medium text-faber-text-muted text-sm">Status</th>
              <th class="text-left p-3 font-medium text-faber-text-muted text-sm">Updated</th>
              <th class="text-right p-3"></th>
            </tr>
          </thead>
          <tbody>
            ${{items.map(item => `
              <tr class="border-b border-faber-border/50 hover:bg-faber-surface-hover">
                <td class="p-3 text-faber-text">$${{item.data?.title || 'Untitled'}}</td>
                <td class="p-3 text-sm text-faber-text-muted">$${{item.collection || 'unknown'}}</td>
                <td class="p-3">
                  <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium
                    ${{item.status === 'published' ? 'bg-green-100 text-green-800' : 
                       item.status === 'draft' ? 'bg-yellow-100 text-yellow-800' : 'bg-gray-100 text-gray-800'}}
                  ">
                    $${{item.status}}
                  </span>
                </td>
                <td class="p-3 text-sm text-faber-text-muted">$${{item.updated_at ? new Date(item.updated_at).toLocaleDateString() : '—'}}</td>
                <td class="p-3 text-right">
                  <a href="/admin/content/$${{item.collection}}/$${{item.id}}" class="text-sm text-faber-primary hover:underline">Edit</a>
                </td>
              </tr>
            `).join('')}}
          </tbody>
        </table>
      `;
      document.getElementById('recent-content').innerHTML = html;
    }}

    // Initialize
    loadStats();
    loadRecentContent();
  </script>
</BaseLayout>
"""

    # Content List page
    pages["content.astro"] = f"""---
// ContentList.astro - Content Collections List
// Generated by faber-cms for {project_name}

import BaseLayout from "@/layouts/BaseLayout.astro";
import Sidebar from "@/components/admin/Sidebar.astro";
import Header from "@/components/admin/Header.astro";
---

<BaseLayout title="Content | CMS Admin" description="Manage your content collections">
  <div class="flex h-screen bg-faber-background">
    <Sidebar active="/admin/content" />
    <div class="flex-1 flex flex-col min-w-0">
      <Header title="Content" subtitle="Manage collections and entries" />
      <main class="flex-1 p-6 md:p-8 overflow-auto">
        <div class="mb-6 flex items-center justify-between">
          <h2 class="text-xl font-semibold text-faber-text">Collections</h2>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4" id="collections-grid">
          <div class="bg-faber-surface border border-faber-border rounded-xl p-6 animate-pulse">
            <div class="h-6 w-1/3 bg-faber-border rounded mb-4"></div>
            <div class="h-4 w-full bg-faber-border rounded mb-2"></div>
            <div class="h-4 w-2/3 bg-faber-border rounded"></div>
          </div>
          <div class="bg-faber-surface border border-faber-border rounded-xl p-6 animate-pulse">
            <div class="h-6 w-1/3 bg-faber-border rounded mb-4"></div>
            <div class="h-4 w-full bg-faber-border rounded mb-2"></div>
            <div class="h-4 w-2/3 bg-faber-border rounded"></div>
          </div>
        </div>
      </main>
    </div>
  </div>

  <script is:inline>
    const WORKER_URL = "{worker_url}";

    async function loadCollections() {{
      try {{
        const response = await fetch(`${{WORKER_URL}}/api/collections`);
        if (response.ok) {{
          const data = await response.json();
          renderCollections(data.items || []);
        }} else {{
          document.getElementById('collections-grid').innerHTML = 
            '<div class="col-span-full p-6 text-center text-faber-text-muted">Failed to load collections</div>';
        }}
      }} catch (e) {{
        console.warn('Could not load collections:', e);
        document.getElementById('collections-grid').innerHTML = 
          '<div class="col-span-full p-6 text-center text-faber-text-muted">Unable to load collections</div>';
      }}
    }}

    function renderCollections(collections) {{
      if (collections.length === 0) {{
        document.getElementById('collections-grid').innerHTML = `
          <div class="col-span-full text-center py-12">
            <div class="text-4xl mb-4">📂</div>
            <h3 class="text-lg font-medium text-faber-text mb-2">No collections yet</h3>
            <p class="text-faber-text-muted mb-4">Create your first collection in Settings</p>
            <a href="/admin/settings" class="text-faber-primary underline">Go to Settings →</a>
          </div>
        `;
        return;
      }}

      const html = collections.map(c => `
        <a href="/admin/content/${{c.name}}" class="bg-faber-surface border border-faber-border rounded-xl p-6 hover:border-faber-primary/50 transition-colors">
          <h3 class="font-semibold text-faber-text mb-1">${{c.display_name || c.name}}</h3>
          <p class="text-sm text-faber-text-muted mb-4">${{c.description || 'No description'}}</p>
          <div class="flex items-center justify-between text-sm text-faber-text-muted">
            <span>Type: ${{c.content_type_name || 'unknown'}}</span>
            <span>→</span>
          </div>
        </a>
      `).join('');
      document.getElementById('collections-grid').innerHTML = html;
    }}

    loadCollections();
  </script>
</BaseLayout>
"""

    # Content Collection Items page
    pages["content/[collection].astro"] = f"""---
// ContentCollection.astro - Items in a Collection
// Generated by faber-cms for {project_name}

import BaseLayout from "@/layouts/BaseLayout.astro";
import Sidebar from "@/components/admin/Sidebar.astro";
import Header from "@/components/admin/Header.astro";
import ContentTable from "@/components/admin/ContentTable.astro";
import Modal from "@/components/admin/Modal.astro";
import Toast from "@/components/admin/Toast.astro";
---

<BaseLayout title="Content | CMS Admin" description="Manage content items">
  <div class="flex h-screen bg-faber-background">
    <Sidebar active="/admin/content" />
    <div class="flex-1 flex flex-col min-w-0">
      <Header 
        title="Content" 
        subtitle="Browse and manage content items"
        action={{
          label: "New Item",
          href: "/admin/content/{collection}/new"
        }}
      />
      <main class="flex-1 p-6 md:p-8 overflow-auto">
        <ContentTable 
          collection="{collection}" 
          workerUrl="{worker_url}" 
        />
      </main>
      <Modal id="delete-modal" title="Delete Item" message="Are you sure you want to delete this item? This action cannot be undone." />
      <Toast />
    </div>
  </div>
</BaseLayout>
"""

    # Content Editor page
    pages["content/[collection]/[id].astro"] = f"""---
// ContentEditor.astro - Edit Content Item
// Generated by faber-cms for {project_name}

import BaseLayout from "@/layouts/BaseLayout.astro";
import Sidebar from "@/components/admin/Sidebar.astro";
import Header from "@/components/admin/Header.astro";
import ContentForm from "@/components/admin/ContentForm.astro";
import Toast from "@/components/admin/Toast.astro";
---

<BaseLayout title="Edit Content | CMS Admin" description="Edit content item">
  <div class="flex h-screen bg-faber-background">
    <Sidebar active="/admin/content" />
    <div class="flex-1 flex flex-col min-w-0">
      <Header 
        title="Edit Content" 
        subtitle="Modify your content item"
        action={{
          label: "Back to List",
          href: "/admin/content/{collection}"
        }}
      />
      <main class="flex-1 p-6 md:p-8 overflow-auto">
        <ContentForm 
          collection="{collection}" 
          itemId="{id}" 
          workerUrl="{worker_url}" 
        />
      </main>
      <Toast />
    </div>
  </div>
</BaseLayout>
"""

    # Settings page
    pages["settings.astro"] = f"""---
// Settings.astro - CMS Settings
// Generated by faber-cms for {project_name}

import BaseLayout from "@/layouts/BaseLayout.astro";
import Sidebar from "@/components/admin/Sidebar.astro";
import Header from "@/components/admin/Header.astro";
import Modal from "@/components/admin/Modal.astro";
import Toast from "@/components/admin/Toast.astro";
---

<BaseLayout title="Settings | CMS Admin" description="Configure collections and preferences">
  <div class="flex h-screen bg-faber-background">
    <Sidebar active="/admin/settings" />
    <div class="flex-1 flex flex-col min-w-0">
      <Header title="Settings" subtitle="Manage collections and configuration" />
      <main class="flex-1 p-6 md:p-8 overflow-auto">
        <section class="mb-8">
          <h2 class="text-xl font-semibold text-faber-text mb-4">Collections</h2>
          <div class="flex items-center justify-between mb-4">
            <p class="text-faber-text-muted">Manage your content collections and their fields</p>
            <button 
              id="new-collection-btn"
              class="px-4 py-2 bg-faber-primary text-white rounded-lg hover:bg-faber-primary-dark transition-colors"
            >
              New Collection
            </button>
          </div>
          <div class="bg-faber-surface border border-faber-border rounded-xl overflow-hidden" id="collections-table">
            <div class="p-6 text-center text-faber-text-muted">Loading collections...</div>
          </div>
        </section>

        <section>
          <h2 class="text-xl font-semibold text-faber-text mb-4">Worker Configuration</h2>
          <div class="bg-faber-surface border border-faber-border rounded-xl p-6 space-y-4">
            <div>
              <label class="block text-sm font-medium text-faber-text mb-1">Worker API URL</label>
              <input type="url" value="{worker_url}" readonly class="w-full px-3 py-2 border border-faber-border rounded-lg bg-faber-surface text-faber-text text-sm font-mono" />
              <p class="text-xs text-faber-text-muted mt-1">This is the deployed Worker API endpoint. Update in wrangler.toml and redeploy.</p>
            </div>
            <div>
              <label class="block text-sm font-medium text-faber-text mb-1">D1 Database</label>
              <input type="text" value="Configured via wrangler.toml" readonly class="w-full px-3 py-2 border border-faber-border rounded-lg bg-faber-surface text-faber-text text-sm" />
              <p class="text-xs text-faber-text-muted mt-1">Database binding configured in Cloudflare Dashboard.</p>
            </div>
            <div>
              <label class="block text-sm font-medium text-faber-text mb-1">Cloudflare Access</label>
              <input type="text" value="Enabled (JWT validation)" readonly class="w-full px-3 py-2 border border-faber-border rounded-lg bg-faber-surface text-faber-text text-sm" />
              <p class="text-xs text-faber-text-muted mt-1">Admin routes protected by Cloudflare Access.</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  </div>

  <Modal 
    id="collection-modal" 
    title="New Collection" 
    message="Create a new content collection"
    fields={[
      { name: "name", label: "Collection Name (slug)", type: "text", required: true, placeholder: "e.g., pages" },
      { name: "display_name", label: "Display Name", type: "text", required: true, placeholder: "e.g., Pages" },
      { name: "content_type_name", label: "Content Type", type: "select", required: true, options: ["page", "post", "product", "custom"] },
      { name: "description", label: "Description", type: "textarea", required: false, placeholder: "Optional description" },
    ]}
  />
  <Toast />
</BaseLayout>

  <script is:inline>
    const WORKER_URL = "{worker_url}";

    async function loadCollections() {{
      try {{
        const response = await fetch(`${{WORKER_URL}}/api/collections`);
        if (response.ok) {{
          const data = await response.json();
          renderCollections(data.items || []);
        }} else {{
          document.getElementById('collections-table').innerHTML = 
            '<div class="p-6 text-center text-faber-text-muted">Failed to load collections</div>';
        }}
      }} catch (e) {{
        console.warn('Could not load collections:', e);
        document.getElementById('collections-table').innerHTML = 
          '<div class="p-6 text-center text-faber-text-muted">Unable to load collections</div>';
      }}
    }}

    function renderCollections(collections) {{
      if (collections.length === 0) {{
        document.getElementById('collections-table').innerHTML = `
          <div class="p-6 text-center">
            <p class="text-faber-text-muted mb-4">No collections yet</p>
            <button id="new-collection-btn-2" class="px-4 py-2 bg-faber-primary text-white rounded-lg hover:bg-faber-primary-dark transition-colors">
              Create First Collection
            </button>
          </div>
        `;
        document.getElementById('new-collection-btn-2')?.addEventListener('click', () => {{
          document.getElementById('collection-modal')?.showModal();
        }});
        return;
      }}

      const html = `
        <table class="w-full">
          <thead>
            <tr class="border-b border-faber-border">
              <th class="text-left p-3 font-medium text-faber-text-muted text-sm">Name</th>
              <th class="text-left p-3 font-medium text-faber-text-muted text-sm">Display Name</th>
              <th class="text-left p-3 font-medium text-faber-text-muted text-sm">Type</th>
              <th class="text-right p-3 font-medium text-faber-text-muted text-sm">Actions</th>
            </tr>
          </thead>
          <tbody>
            ${{collections.map(c => `
              <tr class="border-b border-faber-border/50 hover:bg-faber-surface-hover">
                <td class="p-3 text-faber-text font-mono text-sm">${{c.name}}</td>
                <td class="p-3 text-faber-text">${{c.display_name || c.name}}</td>
                <td class="p-3 text-sm text-faber-text-muted">${{c.content_type_name || 'unknown'}}</td>
                <td class="p-3 text-right">
                  <a href="/admin/content/${{c.name}}" class="text-sm text-faber-primary hover:underline mr-3">Manage</a>
                  <button class="text-sm text-faber-danger hover:underline" data-collection="${{c.name}}" data-action="delete">Delete</button>
                </td>
              </tr>
            `).join('')}}
          </tbody>
        </table>
      `;
      document.getElementById('collections-table').innerHTML = html;
    }}

    // Modal handling
    const collectionModal = document.getElementById('collection-modal');
    const newCollectionBtn = document.getElementById('new-collection-btn');
    const newCollectionBtn2 = document.getElementById('new-collection-btn-2');

    [newCollectionBtn, newCollectionBtn2].forEach(btn => {{
      if (btn) {{
        btn.addEventListener('click', () => {{
          collectionModal?.showModal();
        }});
      }}
    }});

    collectionModal?.addEventListener('close', () => {{
      collectionModal.querySelector('form')?.reset();
    }});

    collectionModal?.querySelector('form')?.addEventListener('submit', async (e) => {{
      e.preventDefault();
      const formData = new FormData(e.target);
      const data = Object.fromEntries(formData.entries());

      try {{
        const response = await fetch(`${{WORKER_URL}}/api/collections`, {{
          method: 'POST',
          headers: {{ 'Content-Type': 'application/json' }},
          body: JSON.stringify(data),
        }});

        if (response.ok) {{
          collectionModal.close();
          loadCollections();
          showToast('Collection created successfully', 'success');
        }} else {{
          const error = await response.json();
          showToast(error.message || 'Failed to create collection', 'error');
        }}
      }} catch (err) {{
        showToast('Network error', 'error');
      }}
    }});

    function showToast(message, type = 'info') {{
      const toast = document.querySelector('toast-component');
      if (toast && toast.show) {{
        toast.show(message, type);
      }} else {{
        alert(message);
      }}
    }}

    loadCollections();
  </script>
</BaseLayout>
"""

    return pages


if __name__ == "__main__":
    print("Use via generate_admin_ui.py")