#!/usr/bin/env python3
"""
Faber CMS Generator - Iteration A

Generates a Cloudflare Worker-based CMS with D1 SQLite database.
Produces: Worker TypeScript code, D1 schema/migrations, wrangler.toml, REST API.
"""

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional

import typer

app = typer.Typer(help="Faber CMS Generator - Iteration A: Worker + D1 + REST API")


def run_cmd(cmd: List[str], cwd: Optional[Path] = None, env: Optional[Dict] = None) -> subprocess.CompletedProcess:
    """Run command and return result."""
    merged_env = {**os.environ}
    if env:
        merged_env.update(env)
    return subprocess.run(cmd, capture_output=True, text=True, cwd=cwd, env=merged_env)


def generate_content_type_sql(content_type: Dict[str, Any]) -> str:
    """Generate SQL CREATE TABLE for a content type."""
    name = content_type["name"]
    fields = content_type.get("fields", [])

    columns = [
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "collection_id INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE",
        "version INTEGER NOT NULL DEFAULT 1",
        "data JSON NOT NULL",
        "status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived'))",
        "created_at DATETIME DEFAULT CURRENT_TIMESTAMP",
        "updated_at DATETIME DEFAULT CURRENT_TIMESTAMP",
        "published_at DATETIME",
        "created_by TEXT",
        "updated_by TEXT",
    ]

    has_slug = any(f["name"] == "slug" for f in fields)
    if has_slug:
        columns.append("UNIQUE(collection_id, slug)")

    sql = "CREATE TABLE IF NOT EXISTS content_{name} (\n  ".format(name=name) + ",\n  ".join(columns) + "\n);"

    sql += "\nCREATE INDEX IF NOT EXISTS idx_content_{name}_collection ON content_{name}(collection_id);".format(name=name)
    sql += "\nCREATE INDEX IF NOT EXISTS idx_content_{name}_status ON content_{name}(status);".format(name=name)
    if has_slug:
        sql += "\nCREATE INDEX IF NOT EXISTS idx_content_{name}_slug ON content_{name}(slug);".format(name=name)
    sql += "\nCREATE INDEX IF NOT EXISTS idx_content_{name}_published_at ON content_{name}(published_at);".format(name=name)

    return sql


def generate_d1_schema(content_types: List[Dict[str, Any]]) -> str:
    """Generate complete D1 schema SQL."""
    lines = [
        "-- Faber CMS D1 Schema",
        "-- Generated by faber-cms skill",
        "",
        "-- Collections table (groups content types)",
        "CREATE TABLE IF NOT EXISTS collections (",
        "  id INTEGER PRIMARY KEY AUTOINCREMENT,",
        "  name TEXT NOT NULL UNIQUE,",
        "  display_name TEXT NOT NULL,",
        "  description TEXT,",
        "  content_type_name TEXT NOT NULL,",
        "  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,",
        "  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP",
        ");",
        "",
        "-- Content versions table (audit trail)",
        "CREATE TABLE IF NOT EXISTS content_versions (",
        "  id INTEGER PRIMARY KEY AUTOINCREMENT,",
        "  content_id INTEGER NOT NULL,",
        "  collection_id INTEGER NOT NULL,",
        "  version INTEGER NOT NULL,",
        "  data JSON NOT NULL,",
        "  status TEXT NOT NULL,",
        "  changed_by TEXT,",
        "  change_summary TEXT,",
        "  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,",
        "  FOREIGN KEY (content_id, collection_id) REFERENCES content_items(id, collection_id) ON DELETE CASCADE",
        ");",
        "",
        "CREATE INDEX IF NOT EXISTS idx_content_versions_content ON content_versions(content_id, collection_id);",
        "CREATE INDEX IF NOT EXISTS idx_content_versions_created ON content_versions(created_at);",
        "",
    ]

    for ct in content_types:
        lines.append("-- Content type: {0}".format(ct['name']))
        lines.append(generate_content_type_sql(ct))
        lines.append("")

    lines.append("-- Unified content view")
    lines.append("CREATE VIEW IF NOT EXISTS content_items AS")
    if content_types:
        union_parts = []
        for ct in content_types:
            union_parts.append("SELECT id, collection_id, version, data, status, created_at, updated_at, published_at, created_by, updated_by, 'content_{0}' as source_table FROM content_{0}".format(ct['name']))
        lines.append(" UNION ALL ".join(union_parts) + ";")
    else:
        lines.append("SELECT 0 as id, 0 as collection_id, 0 as version, '{}' as data, 'draft' as status, datetime('now') as created_at, datetime('now') as updated_at, null as published_at, null as created_by, null as updated_by, 'none' as source_table WHERE 0;")
    lines.append("")

    return "\n".join(lines)


def generate_migration_sql(content_types: List[Dict[str, Any]]) -> str:
    return """-- Migration: 0001_initial_schema
-- Generated by faber-cms skill

{0}
""".format(generate_d1_schema(content_types))


def generate_wrangler_toml(project_name: str, config: Dict[str, Any]) -> str:
    production_domain = config.get("deploy_targets", {}).get("production", {}).get("domain", "{0}.example.com".format(project_name))
    staging_domain = config.get("deploy_targets", {}).get("staging", {}).get("domain", "dev-{0}.example.com".format(project_name))
    d1_name = "{0}-db".format(project_name)

    cf_access = config.get("cf_access_policy", {})
    access_emails = cf_access.get("emails", ["admin@example.com"])
    access_groups = cf_access.get("groups", [])

    return """name = "{project_name}"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "{d1_name}"
database_id = "<your-d1-database-id>"

# KV namespace for sessions/cache
[[kv_namespaces]]
binding = "SESSIONS"
id = "<your-kv-namespace-id>"
preview_id = "<your-preview-kv-namespace-id>"

# Cloudflare Access configuration
[vars]
CF_ACCESS_TEAM_DOMAIN = "<your-team>.cloudflareaccess.com"
CF_ACCESS_AUD = "{aud}"
ENVIRONMENT = "production"

# Production domain: {production_domain}
# Staging domain: {staging_domain}

[triggers]
crons = ["0 * * * *"]  # Hourly cleanup job

[build]
command = "npm run build"
watch_dir = "src"

[dev]
port = 8787
ip = "127.0.0.1"
""".format(
        project_name=project_name,
        d1_name=d1_name,
        aud=",".join(access_emails + access_groups),
        production_domain=production_domain,
        staging_domain=staging_domain,
    )


def generate_package_json(project_name: str) -> str:
    return json.dumps({
        "name": project_name,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": {
            "dev": "wrangler dev",
            "build": "tsc && wrangler deploy --dry-run",
            "deploy:staging": "wrangler deploy --env staging",
            "deploy:production": "wrangler deploy --env production",
            "typecheck": "tsc --noEmit",
            "lint": "eslint src --ext .ts",
            "test": "vitest run",
            "db:generate": "drizzle-kit generate:sqlite",
            "db:migrate": "wrangler d1 migrations apply DB --remote",
            "db:studio": "wrangler d1 execute DB --remote --command '.schema'"
        },
        "dependencies": {
            "hono": "^4.0.0",
            "drizzle-orm": "^0.30.0",
            "zod": "^3.22.0",
            "@cloudflare/kv-asset-handler": "^0.3.0"
        },
        "devDependencies": {
            "@cloudflare/workers-types": "^4.2024000.0",
            "@types/node": "^20.0.0",
            "drizzle-kit": "^0.20.0",
            "typescript": "^5.4.0",
            "vitest": "^1.4.0",
            "wrangler": "^3.30.0",
            "eslint": "^8.56.0",
            "@typescript-eslint/eslint-plugin": "^7.0.0",
            "@typescript-eslint/parser": "^7.0.0"
        },
        "engines": {
            "node": ">=18.14.1"
        }
    }, indent=2)


def generate_tsconfig() -> str:
    return json.dumps({
        "compilerOptions": {
            "target": "ES2022",
            "module": "ESNext",
            "moduleResolution": "bundler",
            "lib": ["ES2022"],
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "skipLibCheck": True,
            "forceConsistentCasingInFileNames": True,
            "resolveJsonModule": True,
            "isolatedModules": True,
            "noUncheckedIndexedAccess": True,
            "types": ["@cloudflare/workers-types"]
        },
        "include": ["src/**/*", "worker-configuration.d.ts"],
        "exclude": ["node_modules", "dist"]
    }, indent=2)


def generate_worker_index(content_types: List[Dict[str, Any]]) -> str:
    ct_names = [ct["name"] for ct in content_types]
    collections = ", ".join('"{0}"'.format(name) for name in ct_names)

    template = """// Faber CMS Worker - Generated by faber-cms skill
// Iteration A: Worker + D1 + REST API + CF Access

import {{ Hono }} from "hono";
import {{ cors }} from "hono/cors";
import {{ logger }} from "hono/logger";
import {{ secureHeaders }} from "hono/secure-headers";
import {{ cfAccessMiddleware }} from "./middleware/cf-access";
import {{ contentRoutes }} from "./routes/content";
import {{ collectionsRoutes }} from "./routes/collections";
import {{ healthRoutes }} from "./routes/health";
import type {{ Env }} from "./types";

const app = new Hono<Env>();

// Global middleware
app.use("*", logger());
app.use("*", secureHeaders());
app.use("*", cors({{
  origin: ["https://{collections}.example.com", "https://dev-{collections}.example.com"],
  allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
  allowHeaders: ["Content-Type", "Authorization", "CF-Access-Jwt-Assertion"],
  credentials: true,
}}));

// CF Access protection for admin routes
app.use("/api/*", cfAccessMiddleware);

// Routes
app.route("/api/health", healthRoutes);
app.route("/api/content", contentRoutes);
app.route("/api/collections", collectionsRoutes);

// 404 handler
app.notFound((c) => c.json({{ error: "Not found", path: c.req.path }}, 404));

// Error handler
app.onError((err, c) => {{
  console.error("Worker error:", err);
  return c.json({{ error: "Internal server error" }}, 500);
}});

export default app;
"""
    return template.format(collections=collections)


def generate_types_ts(content_types: List[Dict[str, Any]]) -> str:
    lines = [
        "// Generated types for Faber CMS",
        "",
        "import { z } from \"zod\";",
        "",
        "export interface Env {",
        "  DB: D1Database;",
        "  SESSIONS: KVNamespace;",
        "  CF_ACCESS_TEAM_DOMAIN: string;",
        "  CF_ACCESS_AUD: string;",
        "}",
        "",
    ]

    for ct in content_types:
        name = ct["name"]
        fields = ct.get("fields", [])

        field_defs = []
        for field in fields:
            ts_type = {
                "string": "z.string()",
                "markdown": "z.string()",
                "boolean": "z.boolean()",
                "datetime": "z.string().datetime()",
                "array": "z.array(z.string())",
                "number": "z.number()",
            }.get(field["type"], "z.any()")

            if field.get("required", False):
                field_defs.append("  {0}: {1},".format(field["name"], ts_type))
            else:
                field_defs.append("  {0}: {1}.optional(),".format(field["name"], ts_type))

        lines.extend([
            "// {0} content type".format(name),
            "export const {0}Schema = z.object({{".format(name),
            *field_defs,
            "});",
            "export type {0} = z.infer<typeof {0}Schema>;".format(name.capitalize()),
            "",
        ])

    return "\n".join(lines)


def generate_cf_access_middleware() -> str:
    return """// Cloudflare Access middleware
// Validates CF-Access-Jwt-Assertion header

import { createMiddleware } from "hono/factory";
import { verify } from "hono/jwt";
import type { Env } from "../types";

export const cfAccessMiddleware = createMiddleware<Env>(async (c, next) => {
  const teamDomain = c.env.CF_ACCESS_TEAM_DOMAIN;
  const expectedAud = c.env.CF_ACCESS_AUD.split(",").map(s => s.trim());

  // Get JWT from header
  const jwt = c.req.header("CF-Access-Jwt-Assertion");
  if (!jwt) {
    return c.json({ error: "Authentication required: CF-Access-Jwt-Assertion header missing" }, 401);
  }

  try {
    // Fetch public keys from Cloudflare Access
    const jwksUrl = "https://${teamDomain}/cdn-cgi/access/certs";
    const jwksResponse = await fetch(jwksUrl);
    if (!jwksResponse.ok) {
      throw new Error("Failed to fetch JWKS");
    }
    const jwks = await jwksResponse.json();

    // Verify JWT
    const payload = await verify(jwt, jwks.keys[0], "RS256");

    // Validate audience
    const aud = Array.isArray(payload.aud) ? payload.aud : [payload.aud];
    const validAud = aud.some(a => expectedAud.includes(a));
    if (!validAud) {
      return c.json({ error: "Invalid audience" }, 403);
    }

    // Extract user info
    const email = payload.email || payload.sub;
    c.set("cfAccessUser", { email, groups: payload.groups || [] });

    await next();
  } catch (err) {
    console.error("CF Access validation failed:", err);
    return c.json({ error: "Authentication failed" }, 401);
  }
};
"""


def generate_content_routes(content_types: List[Dict[str, Any]]) -> str:
    ct_names = [ct["name"] for ct in content_types]

    template = """// Content CRUD routes
import {{ Hono }} from "hono";
import {{ zValidator }} from "@hono/zod-validator";
import {{ z }} from "zod";
import type {{ Env }} from "../types";
import {{ z }} from "zod";

const contentRoutes = new Hono<Env>();

// List content items with pagination, filtering
contentRoutes.get("/", async (c) => {{
  const collection = c.req.query("collection");
  const status = c.req.query("status") || "published";
  const limit = parseInt(c.req.query("limit") || "20");
  const offset = parseInt(c.req.query("offset") || "0");
  const search = c.req.query("search");

  if (!collection) {{
    return c.json({{ error: "collection query param required" }}, 400);
  }}

  const db = c.env.DB;
  let query = `
    SELECT * FROM content_items
    WHERE source_table = ?
    AND status = ?
  `;
  const params = ["content_{{collection}}", status];

  if (search) {{
    query += " AND data LIKE ?";
    params.push("%" + search + "%");
  }}

  query += " ORDER BY updated_at DESC LIMIT ? OFFSET ?";
  params.push(limit, offset);

  const results = await db.prepare(query).bind(...params).all();
  const total = await db.prepare(
    "SELECT COUNT(*) as count FROM content_items WHERE source_table = ? AND status = ?"
  ).bind("content_{{collection}}", status).first();

  return c.json({{
    items: results.results,
    pagination: {{
      limit,
      offset,
      total: total?.count || 0,
    }},
  }});
}});

// Get single content item by ID
contentRoutes.get("/:id", async (c) => {{
  const id = c.req.param("id");
  const collection = c.req.query("collection");

  if (!collection) {{
    return c.json({{ error: "collection query param required" }}, 400);
  }}

  const item = await c.env.DB.prepare(
    "SELECT * FROM content_{{collection}} WHERE id = ?"
  ).bind(id).first();

  if (!item) {{
    return c.json({{ error: "Not found" }}, 404);
  }}

  return c.json(item);
}});

// Create content item
const createSchema = z.object({{
  collection: z.string(),
  data: z.record(z.any()),
  status: z.enum(["draft", "published", "archived"]).default("draft"),
}});

contentRoutes.post("/", zValidator("json", createSchema), async (c) => {{
  const {{ collection, data, status }} = c.req.valid("json");
  const user = c.get("cfAccessUser")?.email || "system";

  const db = c.env.DB;
  const now = new Date().toISOString();

  // Build INSERT query dynamically based on status
  let columns = "collection_id, data, status, created_at, updated_at, created_by, updated_by";
  let placeholders = "?, ?, ?, ?, ?, ?, ?";
  let values = [
    1, // collection_id - would lookup from collections table
    JSON.stringify(data),
    status,
    now,
    now,
    user,
    user
  ];

  if (status === "published") {{
    columns += ", published_at";
    placeholders += ", ?";
    values.push(now);
  }}

  const result = await db.prepare(`
    INSERT INTO content_{{collection}} (${{columns}}) VALUES (${{placeholders}})
  `).bind(...values).run();

  const newId = result.meta.last_row_id;
  const newItem = await db.prepare("SELECT * FROM content_{{collection}} WHERE id = ?").bind(newId).first();

  return c.json(newItem, 201);
}});

// Update content item
const updateSchema = z.object({{
  collection: z.string(),
  data: z.record(z.any()).optional(),
  status: z.enum(["draft", "published", "archived"]).optional(),
}});

contentRoutes.put("/:id", zValidator("json", updateSchema), async (c) => {{
  const id = c.req.param("id");
  const {{ collection, data, status }} = c.req.valid("json");
  const user = c.get("cfAccessUser")?.email || "system";

  if (!data && !status) {{ return c.json({{ error: "No fields to update" }}, 400); }}
      
      const db = c.env.DB;
      const now = new Date().toISOString();

      // Build dynamic update
      const updates = ["updated_at = ?", "updated_by = ?", "version = version + 1"];
      const params = [now, user];

      if (data) {{
        updates.push("data = ?");
        params.push(JSON.stringify(data));
      }}
      if (status) {{
        updates.push("status = ?");
        params.push(status);
        if (status === "published") {{
          updates.push("published_at = ?");
          params.push(now);
        }}
      }}

      params.push(id);

      await db.prepare(`
        UPDATE content_{{collection}} SET ${{updates.join(", ")}} WHERE id = ?
      `).bind(...params).run();

      const updated = await db.prepare("SELECT * FROM content_{{collection}} WHERE id = ?").bind(id).first();
      return c.json(updated);
    }});

    // Delete content item (soft delete - archives)
    contentRoutes.delete("/:id", async (c) => {{
      const id = c.req.param("id");
      const collection = c.req.query("collection");

      if (!collection) {{
        return c.json({{ error: "collection query param required" }}, 400);
      }}

      await c.env.DB.prepare(
        "UPDATE content_{{collection}} SET status = 'archived', updated_at = ? WHERE id = ?"
      ).bind(new Date().toISOString(), id).run();

      return c.json({{ success: true }});
    }});

    export {{ contentRoutes }};
    """
    return template.format(
        collections=", ".join(ct_names),
        collection="{collection}"
    )


def generate_collections_routes() -> str:
    return """// Collections management routes
import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";
import type { Env } from "../types";

const collectionsRoutes = new Hono<Env>();

// List collections
collectionsRoutes.get("/", async (c) => {
  const collections = await c.env.DB.prepare(
    "SELECT * FROM collections ORDER BY name"
  ).all();
  return c.json(collections.results);
});

// Get collection by name
collectionsRoutes.get("/:name", async (c) => {
  const name = c.req.param("name");
  const collection = await c.env.DB.prepare(
    "SELECT * FROM collections WHERE name = ?"
  ).bind(name).first();

  if (!collection) {
    return c.json({ error: "Collection not found" }, 404);
  }

  return c.json(collection);
});

// Create collection
const createCollectionSchema = z.object({
  name: z.string().min(1).max(100),
  displayName: z.string().min(1).max(200),
  description: z.string().optional(),
  contentTypeName: z.string().min(1),
});

collectionsRoutes.post("/", zValidator("json", createCollectionSchema), async (c) => {
  const { name, displayName, description, contentTypeName } = c.req.valid("json");

  const result = await c.env.DB.prepare(
    "INSERT INTO collections (name, display_name, description, content_type_name) VALUES (?, ?, ?, ?)"
  ).bind(name, displayName, description || "", contentTypeName).run();

  const newId = result.meta.last_row_id;
  const collection = await c.env.DB.prepare("SELECT * FROM collections WHERE id = ?").bind(newId).first();

  return c.json(collection, 201);
});

export { collectionsRoutes };
"""


def generate_health_routes() -> str:
    return """// Health check routes
import { Hono } from "hono";
import type { Env } from "../types";

const healthRoutes = new Hono<Env>();

healthRoutes.get("/", async (c) => {
  try:
    // Test D1 connectivity
    const result = await c.env.DB.prepare("SELECT 1 as healthy").first();
    const dbHealthy = result?.healthy === 1;

    return c.json({
      status: dbHealthy ? "healthy" : "unhealthy",
      database: dbHealthy ? "connected" : "disconnected",
      timestamp: new Date().toISOString(),
    }, dbHealthy ? 200 : 503);
  } catch (err) {
    return c.json({
      status: "unhealthy",
      database: "error",
      error: String(err),
      timestamp: new Date().toISOString(),
    }, 503);
  }
});

export { healthRoutes };
"""


def write_file(path: Path, content: str):
    """Write file, creating parent dirs."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    typer.secho("  ✓ " + str(path), fg=typer.colors.GREEN)


@app.command()
def generate(
    project_name: str = typer.Option("faber-cms", "--project-name", "-n"),
    output_dir: str = typer.Option("./faber-cms", "--output-dir", "-o"),
    content_types: str = typer.Option("[]", "--content-types", help="JSON array of content type definitions"),
    content_types_file: Optional[str] = typer.Option(None, "--content-types-file", help="Path to JSON file with content types"),
    production_domain: str = typer.Option("cms.example.com", "--production-domain"),
    staging_domain: str = typer.Option("dev-cms.example.com", "--staging-domain"),
    cf_access_emails: str = typer.Option("admin@example.com", "--cf-access-emails", help="Comma-separated emails for CF Access"),
    cf_access_groups: str = typer.Option("", "--cf-access-groups", help="Comma-separated groups for CF Access"),
):
    """Generate Faber CMS Worker project (Iteration A)."""
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    # Parse content types
    if content_types_file:
        with open(content_types_file) as f:
            ct_data = json.load(f)
    else:
        ct_data = json.loads(content_types)

    if not isinstance(ct_data, list):
        ct_data = [ct_data]

    config = {
        "deploy_targets": {
            "production": {"domain": production_domain, "branch": "main"},
            "staging": {"domain": staging_domain, "branch": "dev"},
        },
        "cf_access_policy": {
            "emails": [e.strip() for e in cf_access_emails.split(",") if e.strip()],
            "groups": [g.strip() for g in cf_access_groups.split(",") if g.strip()],
        },
    }

    typer.secho(f"\nGenerating Faber CMS for '{project_name}'...", fg=typer.colors.BLUE, bold=True)
    typer.secho(f"Output: {out}", fg=typer.colors.CYAN)
    typer.secho(f"Content types: {[ct['name'] for ct in ct_data]}", fg=typer.colors.CYAN)
    typer.secho(f"Production: {production_domain}", fg=typer.colors.CYAN)
    typer.secho(f"Staging: {staging_domain}", fg=typer.colors.CYAN)

    # Generate files
    typer.secho("\n1. Generating D1 schema & migrations...", fg=typer.colors.YELLOW)
    write_file(out / "worker" / "src" / "db" / "schema.sql", generate_d1_schema(ct_data))
    write_file(out / "worker" / "src" / "db" / "migrations" / "0001_initial.sql", generate_migration_sql(ct_data))

    typer.secho("\n2. Generating Worker TypeScript...", fg=typer.colors.YELLOW)
    write_file(out / "worker" / "src" / "index.ts", generate_worker_index(ct_data))
    write_file(out / "worker" / "src" / "types.ts", generate_types_ts(ct_data))
    write_file(out / "worker" / "src" / "middleware" / "cf-access.ts", generate_cf_access_middleware())
    write_file(out / "worker" / "src" / "routes" / "content.ts", generate_content_routes(ct_data))
    write_file(out / "worker" / "src" / "routes" / "collections.ts", generate_collections_routes())
    write_file(out / "worker" / "src" / "routes" / "health.ts", generate_health_routes())

    typer.secho("\n3. Generating config files...", fg=typer.colors.YELLOW)
    write_file(out / "worker" / "wrangler.toml", generate_wrangler_toml(project_name, {
        "deploy_targets": {
            "production": {"domain": production_domain, "branch": "main"},
            "staging": {"domain": staging_domain, "branch": "dev"}
        },
        "cf_access_policy": {
            "emails": [e.strip() for e in cf_access_emails.split(",") if e.strip()],
            "groups": [g.strip() for g in cf_access_groups.split(",") if g.strip()],
        },
    }))
    write_file(out / "worker" / "package.json", generate_package_json(project_name))
    write_file(out / "worker" / "tsconfig.json", generate_tsconfig())

    typer.secho("\n4. Generating CI/CD workflow...", fg=typer.colors.YELLOW)
    write_file(out / "worker" / ".github" / "workflows" / "deploy.yml", generate_ci_workflow(project_name, {
        "deploy_targets": {
            "production": {"domain": production_domain, "branch": "main"},
            "staging": {"domain": staging_domain, "branch": "dev"}
        }
    }))

    typer.secho(f"\n✅ Faber CMS (Iteration A) generated at: {out}", fg=typer.colors.GREEN, bold=True)
    typer.secho("\nNext steps:", fg=typer.colors.BLUE)
    typer.echo(f"  cd {out}/worker")
    typer.echo("  npm install")
    typer.echo("  npm run dev        # Local development")
    typer.echo("  npm run build      # Production build")
    typer.echo("\nDeploy targets (per FRAMEWORK.md §13):")
    typer.echo("  main  → " + production_domain + " (production)")
    typer.echo("  dev   → " + staging_domain + " (staging)")


def generate_ci_workflow(project_name: str, config: Dict) -> str:
    prod_domain = config.get("deploy_targets", {}).get("production", {}).get("domain", "{0}.example.com".format(project_name))
    staging_domain = config.get("deploy_targets", {}).get("staging", {}).get("domain", "dev-{0}.example.com".format(project_name))

    lines = [
        "name: Deploy CMS Worker",
        "",
        "on:",
        "  push:",
        "    branches: [dev, main]",
        "  pull_request:",
        "    branches: [dev, main]",
        "",
        "jobs:",
        "  lint-and-test:",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "",
        "      - name: Setup Node.js",
        "        uses: actions/setup-node@v4",
        "        with:",
        "          node-version: \"20\"",
        "          cache: \"npm\"",
        "          cache-dependency-path: worker/package-lock.json",
        "",
        "      - name: Install dependencies",
        "        run: npm ci",
        "        working-directory: ./worker",
        "",
        "      - name: Run linter",
        "        run: npm run lint",
        "        working-directory: ./worker",
        "",
        "      - name: Run typecheck",
        "        run: npm run typecheck",
        "        working-directory: ./worker",
        "",
        "      - name: Run tests",
        "        run: npm test",
        "        working-directory: ./worker",
        "",
        "      - name: Build",
        "        run: npm run build",
        "        working-directory: ./worker",
        "",
        "  deploy-staging:",
        "    needs: lint-and-test",
        "    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "",
        "      - name: Setup Node.js",
        "        uses: actions/setup-node@v4",
        "        with:",
        "          node-version: \"20\"",
        "          cache: \"npm\"",
        "          cache-dependency-path: worker/package-lock.json",
        "",
        "      - name: Install dependencies",
        "        run: npm ci",
        "        working-directory: ./worker",
        "",
        "      - name: Build",
        "        run: npm run build",
        "        working-directory: ./worker",
        "",
        "      - name: Deploy to Cloudflare Pages Staging",
        "        uses: cloudflare/pages-action@v1",
        "        with:",
        "          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}",
        "          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}",
        "          projectName: " + project_name + "-staging",
        "          directory: ./worker/dist",
        "          branch: dev",
        "",
        "  deploy-production:",
        "    needs: lint-and-test",
        "    if: github.event_name == 'push' && github.ref == 'refs/heads/main'",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "",
        "      - name: Setup Node.js",
        "        uses: actions/setup-node@v4",
        "        with:",
        "          node-version: \"20\"",
        "          cache: \"npm\"",
        "          cache-dependency-path: worker/package-lock.json",
        "",
        "      - name: Install dependencies",
        "        run: npm ci",
        "        working-directory: ./worker",
        "",
        "      - name: Build",
        "        run: npm run build",
        "        working-directory: ./worker",
        "",
        "      - name: Deploy to Cloudflare Pages Production",
        "        uses: cloudflare/pages-action@v1",
        "        with:",
        "          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}",
        "          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}",
        "          projectName: " + project_name,
        "          directory: ./worker/dist",
        "          branch: main",
        "",
        "# Deploy targets per FRAMEWORK.md §13:",
        "# main  → Production (" + prod_domain + ")",
        "# dev   → Staging (" + staging_domain + ")",
        "# PR    → Preview (ephemeral, continue-on-error: true)",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    app()