#!/usr/bin/env python3
"""
Domain Suggest Skill - Main CLI entry point.

Given a project brief (spec.md, trajectory.md, scope-baseline.md), 
probes RDAP/whois services to generate 3 production domain name candidates 
with rationale (memorability, availability, TLD fit). 
Output must be deterministic for the same brief; human selects one.
Implements FRAMEWORK.md §13 rule 4: domain-suggest skill.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Any, List

# Add scripts directory to path for imports
SCRIPTS_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPTS_DIR))

from generators import generate_domains_from_brief, load_config
from validators import validate_brief_input, validate_output_structure, validate_no_fabrication


def load_brief_from_files(input_dir: Path) -> Dict[str, str]:
    """
    Load brief from spec.md, trajectory.md, and scope-baseline.md files.
    
    Args:
        input_dir: Directory containing the brief files
        
    Returns:
        Dictionary with keys 'spec', 'trajectory', 'scope-baseline'
    """
    brief = {}
    for filename in ["spec.md", "trajectory.md", "scope-baseline.md"]:
        filepath = input_dir / filename
        if filepath.exists():
            # Use the filename without .md as the key
            key = filename[:-3]
            brief[key] = filepath.read_text(encoding="utf-8")
        else:
            # File not found - provide empty string
            brief[filename[:-3]] = ""
    
    return brief


def write_output_files(output_dir: Path, base_name: str, 
                      domain_candidates: List[Dict[str, str]]) -> List[str]:
    """
    Write output files: JSON and Markdown report.
    
    Returns:
        List of filenames created
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    artifacts = []
    
    # Write JSON report
    json_data = {
        "domain_candidates": domain_candidates,
        "generated_at": __import__('datetime').datetime.now().isoformat(),
        "count": len(domain_candidates)
    }
    json_file = output_dir / f"{base_name}.json"
    json_file.write_text(json.dumps(json_data, indent=2), encoding="utf-8")
    artifacts.append(json_file.name)
    
    # Write Markdown report
    md_file = output_dir / f"{base_name}.md"
    with open(md_file, "w", encoding="utf-8") as f:
        f.write("# Domain Name Recommendations\n\n")
        f.write("Generated by domain-suggest skill (FRAMEWORK.md §13)\n\n")
        f.write("| Domain | Availability | Rationale |\n")
        f.write("|--------|--------------|-----------|\n")
        for candidate in domain_candidates:
            domain = candidate.get("domain", "")
            avail = candidate.get("availability", "unknown")
            rationale = candidate.get("rationale", "No rationale provided")
            # Escape pipe characters in rationale
            rationale_escaped = rationale.replace("|", "\\|")
            f.write(f"| {domain} | {avail} | {rationale_escaped} |\n")
        f.write("\n---\n")
        f.write("*Recommendations are based on automated checks. Final availability must be verified via registrar.*\n")
    artifacts.append(md_file.name)
    
    return artifacts


def main() -> None:
    """Main entry point for domain-suggest skill."""
    parser = argparse.ArgumentParser(
        description="Generate domain name candidates from project brief"
    )
    parser.add_argument(
        "--input-dir",
        required=True,
        help="Directory containing spec.md, trajectory.md, scope-baseline.md"
    )
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Directory to write output files (default: current)"
    )
    parser.add_argument(
        "--hitl-gate",
        action="store_true",
        help="Enable HITL gate (requires manual confirmation before writing)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be generated without writing files"
    )
    
    args = parser.parse_args()
    
    # Load configuration
    configuration = load_config()
    input_dir = Path(args.input_dir)
    if not input_dir.is_dir():
        print(f"Error: Input directory '{input_dir}' does not exist", file=sys.stderr)
        sys.exit(1)
    
    brief = load_brief_from_files(input_dir)
    
    # Validate input
    is_valid, errors = validate_brief_input(brief)
    if not is_valid:
        print("Input validation FAILED:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        sys.exit(1)
    
    # Generate domain candidates
    try:
        domain_candidates = generate_domains_from_brief(brief, configuration)
    except Exception as e:
        print(f"Error generating domains: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Build output structure
    output = {
        "status": "success",
        "artifacts": [],  # Will be filled after writing files
        "domain_candidates": [
            {
                "domain": c["domain"],
                "rationale": c["rationale"],
                "availability": c["availability"]
            }
            for c in domain_candidates
        ],
        "hitl_gate_required": args.hitl_gate,
        "hitl_gate_passed": True  # Will be updated if HITL gate is used
    }
    
    # Validate output structure
    is_valid, errors = validate_output_structure(output)
    if not is_valid:
        print(f"Output validation failed: {errors}", file=sys.stderr)
        sys.exit(1)
    
    # Check for fabrication
    is_valid, errors = validate_no_fabrication(output, brief)
    if not is_valid:
        print(f"Fabrication check failed: {errors}", file=sys.stderr)
        sys.exit(1)
    
    # Handle HITL gate
    if args.hitl_gate:
        output["hitl_gate_required"] = True
        print("\n=== HITL GATE: Domain Recommendations ===")
        for i, candidate in enumerate(output["domain_candidates"], 1):
            print(f"{i}. {candidate['domain']}")
            print(f"   Availability: {candidate['availability']}")
            print(f"   Rationale: {candidate['rationale']}\n")
        
        response = input("Accept these recommendations? [y/N]: ").strip().lower()
        if response == "y" or response == "yes":
            output["hitl_gate_passed"] = True
            print("HITL gate passed.")
        else:
            output["hitl_gate_passed"] = False
            print("HITL gate failed - no files will be written.")
            if not args.dry_run:
                # Still output JSON to stdout but don't write files
                print(json.dumps(output, indent=2))
                return
    
    # Write output files (unless dry-run)
    if not args.dry_run:
        output_dir = Path(args.output_dir)
        try:
            artifacts = write_output_files(output_dir, "domain-recommendations", output["domain_candidates"])
            output["artifacts"] = artifacts
        except Exception as e:
            print(f"Error writing output files: {e}", file=sys.stderr)
            sys.exit(1)
    
    # Output machine-readable JSON summary
    print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()