#!/usr/bin/env python3
"""
Publish Skill - Lifecycle skill #6: publishes deployed artifacts and releases.

Reads deployment report, creates GitHub Release, publishes to npm/PyPI,
updates changelog, and outputs publication summary.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional, List


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Publish skill - publish releases and artifacts")
    parser.add_argument("--project-dir", required=True, help="Path to scaffolded project directory")
    parser.add_argument("--input-dir", required=True, help="Directory with deployment report and artifacts")
    parser.add_argument("--output-dir", default=".", help="Directory to write publication report")
    parser.add_argument("--hitl-gate", action="store_true", help="Require manual confirmation before publishing")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be published without executing")
    parser.add_argument("--version", help="Override version (default: read from package.json/pyproject.toml)")
    parser.add_argument("--tag", help="Git tag to create (default: v{version})")
    return parser.parse_args()


def load_deployment_report(input_dir: Path) -> Dict[str, Any]:
    """Load and validate deployment report."""
    report_path = input_dir / "deployment-report.json"
    if not report_path.exists():
        raise FileNotFoundError(f"deployment-report.json not found in {input_dir}")

    report = json.loads(report_path.read_text())
    if report.get("status") != "success":
        raise RuntimeError(f"Deployment report indicates failure: status={report.get('status')}")

    return report


def load_evaluation_report(input_dir: Path) -> Optional[Dict[str, Any]]:
    """Load evaluation report if available."""
    report_path = input_dir / "evaluation-report.json"
    if not report_path.exists():
        return None
    try:
        return json.loads(report_path.read_text())
    except json.JSONDecodeError:
        return None


def get_version(project_dir: Path, override: Optional[str] = None) -> str:
    """Get version from package.json or pyproject.toml."""
    if override:
        return override

    # Try package.json first
    pkg_path = project_dir / "package.json"
    if pkg_path.exists():
        try:
            pkg = json.loads(pkg_path.read_text())
            if "version" in pkg:
                return pkg["version"]
        except (json.JSONDecodeError, KeyError):
            pass

    # Try pyproject.toml
    pyproject_path = project_dir / "pyproject.toml"
    if pyproject_path.exists():
        content = pyproject_path.read_text()
        match = re.search(r'version\s*=\s*"([^"]+)"', content)
        if match:
            return match.group(1)

    raise ValueError("Could not determine version from package.json or pyproject.toml")


def get_conventional_commits(project_dir: Path) -> List[str]:
    """Extract conventional commit messages since last tag."""
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "--pretty=format:%s", "HEAD"],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            return [line.strip() for line in result.stdout.split("\n") if line.strip()]
    except Exception:
        pass
    return []


def generate_release_notes(
    eval_report: Optional[Dict[str, Any]],
    deploy_report: Dict[str, Any],
    commits: List[str],
    version: str,
) -> str:
    """Generate release notes from evaluation, deployment, and commits."""
    notes = [f"## Release v{version}", "", f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}", ""]

    # Deployment info
    deploy_url = deploy_report.get("deployment_url", "TODO")
    notes.append(f"**Deployment:** {deploy_url}")

    # Evaluation summary
    if eval_report:
        checks_passed = eval_report.get("checks_passed", "TODO")
        checks_run = eval_report.get("checks_run", "TODO")
        notes.append(f"**Evaluation:** {checks_passed}/{checks_run} checks passed")
        score = eval_report.get("score")
        if score:
            notes.append(f"**Quality Score:** {score:.1%}")

    notes.append("")

    # Conventional commits
    if commits:
        notes.append("### Changes")
        for commit in commits[:20]:  # Limit to 20
            notes.append(f"- {commit}")
        if len(commits) > 20:
            notes.append(f"- ... and {len(commits) - 20} more commits")
        notes.append("")

    notes.append("*Generated by Faber publish skill*")
    return "\n".join(notes)


def hitl_confirm(message: str) -> bool:
    """Prompt for human confirmation."""
    try:
        response = input(f"{message} [y/N]: ").strip().lower()
        return response in ("y", "yes")
    except (EOFError, KeyboardInterrupt):
        return False


def run_command(cmd: List[str], cwd: Path, dry_run: bool = False) -> Dict[str, Any]:
    """Run a command and return result."""
    if dry_run:
        return {"success": True, "command": " ".join(cmd), "dry_run": True}

    try:
        result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=300)
        return {
            "success": result.returncode == 0,
            "command": " ".join(cmd),
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode,
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "command": " ".join(cmd), "error": "Command timed out"}
    except Exception as e:
        return {"success": False, "command": " ".join(cmd), "error": str(e)}


def create_github_release(
    project_dir: Path, tag: str, notes: str, dry_run: bool
) -> Dict[str, Any]:
    """Create GitHub release using gh CLI."""
    if dry_run:
        return {"success": True, "url": "https://TODO.github.com/releases/tag/TODO", "dry_run": True}

    # Check if tag exists
    result = run_command(["git", "rev-parse", "-q", "--verify", f"refs/tags/{tag}"], project_dir)
    tag_exists = result.get("success", False)

    if not tag_exists:
        # Create tag
        result = run_command(["git", "tag", tag], project_dir)
        if not result.get("success", False):
            return result

    # Create release
    cmd = ["gh", "release", "create", tag, "--title", f"Release {tag}", "--notes", notes]
    result = run_command(cmd, project_dir)

    if result.get("success", False):
        # Get release URL
        result = run_command(["gh", "release", "view", tag, "--json", "url"], project_dir)
        if result.get("success", False):
            try:
                release_data = json.loads(result["stdout"])
                result["url"] = release_data.get("url", "")
            except json.JSONDecodeError:
                pass

    return result


def publish_npm(project_dir: Path, dry_run: bool) -> Dict[str, Any]:
    """Publish to npm if configured."""
    pkg_path = project_dir / "package.json"
    if not pkg_path.exists():
        return {"success": True, "skipped": True, "reason": "No package.json"}

    try:
        pkg = json.loads(pkg_path.read_text())
    except json.JSONDecodeError:
        return {"success": True, "skipped": True, "reason": "Invalid package.json"}

    # Check for publishConfig or private flag
    if pkg.get("private", False):
        return {"success": True, "skipped": True, "reason": "Package is private"}

    has_publish_config = "publishConfig" in pkg or "files" in pkg
    if not has_publish_config and "scripts" in pkg and "prepublishOnly" not in pkg.get("scripts", {}):
        # No publish config, might not want to publish
        return {"success": True, "skipped": True, "reason": "No publish configuration"}

    return run_command(["npm", "publish"], project_dir, dry_run=dry_run)


def update_changelog(project_dir: Path, version: str, notes: str, dry_run: bool) -> Dict[str, Any]:
    """Update CHANGELOG.md with new release entry."""
    changelog_path = project_dir / "CHANGELOG.md"

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    entry = f"## [{version}] - {today}\n\n{notes}\n\n"

    if dry_run:
        return {"success": True, "dry_run": True, "changelog_path": str(changelog_path)}

    if changelog_path.exists():
        content = changelog_path.read_text()
    else:
        content = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n"

    # Insert after first heading
    lines = content.split("\n")
    insert_idx = 1
    for i, line in enumerate(lines):
        if line.startswith("# "):
            insert_idx = i + 1
            break

    new_lines = lines[:insert_idx] + ["", entry] + lines[insert_idx:]
    changelog_path.write_text("\n".join(new_lines))

    return {"success": True, "changelog_path": str(changelog_path)}


def write_publication_report(
    output_dir: Path,
    version: str,
    tag: str,
    deploy_report: Dict[str, Any],
    release_result: Dict[str, Any],
    npm_result: Dict[str, Any],
    changelog_result: Dict[str, Any],
    hitl_gate: bool,
    hitl_passed: bool,
    dry_run: bool,
) -> Dict[str, Any]:
    """Write publication report files."""
    output_dir.mkdir(parents=True, exist_ok=True)

    # JSON report
    report = {
        "status": "success",
        "artifacts": ["publication-report.json", "PUBLICATION_SUMMARY.md"],
        "version": version,
        "tag": tag,
        "github_release_url": release_result.get("url", "TODO"),
        "npm_published": npm_result.get("success", False) and not npm_result.get("skipped", False),
        "changelog_updated": changelog_result.get("success", False),
        "hitl_gate_required": hitl_gate,
        "hitl_gate_passed": hitl_passed,
        "dry_run": dry_run,
    }

    (output_dir / "publication-report.json").write_text(json.dumps(report, indent=2))

    # Markdown summary
    md = f"""# Publication Summary

**Status:** {report['status'].upper()}
**Version:** {version}
**Tag:** {tag}
**GitHub Release:** {report['github_release_url']}
**npm Published:** {'Yes' if report['npm_published'] else 'No (skipped or failed)'}
**Changelog Updated:** {'Yes' if report['changelog_updated'] else 'No'}
**HITL Gate:** {'Required' if report['hitl_gate_required'] else 'Not required'}
**HITL Passed:** {'Yes' if report['hitl_gate_passed'] else 'N/A'}
**Dry Run:** {'Yes' if report['dry_run'] else 'No'}

## Release Details

- **Deployment URL:** {deploy_report.get('deployment_url', 'N/A')}
- **Deployment ID:** {deploy_report.get('deployment_id', 'N/A')}

## Release Notes

See [GitHub Release]({report['github_release_url']}) for full notes.

*Generated by Faber publish skill*
"""
    (output_dir / "PUBLICATION_SUMMARY.md").write_text(md)

    return report


def main() -> int:
    args = parse_args()

    project_dir = Path(args.project_dir).resolve()
    input_dir = Path(args.input_dir).resolve()
    output_dir = Path(args.output_dir).resolve()

    # Validate inputs
    if not project_dir.exists():
        print(f"Error: Project directory does not exist: {project_dir}", file=sys.stderr)
        return 1

    if not input_dir.exists():
        print(f"Error: Input directory does not exist: {input_dir}", file=sys.stderr)
        return 1

    try:
        deploy_report = load_deployment_report(input_dir)
    except (FileNotFoundError, RuntimeError) as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    eval_report = load_evaluation_report(input_dir)

    # Get version
    try:
        version = get_version(project_dir, args.version)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    tag = args.tag or f"v{version}"

    # HITL gate
    hitl_passed = True
    if args.hitl_gate:
        if not hitl_confirm(f"Publish version {version} ({tag})?"):
            print("Publication cancelled by user.", file=sys.stderr)
            return 1
        hitl_passed = True

    # Generate release notes
    commits = get_conventional_commits(project_dir)
    notes = generate_release_notes(eval_report, deploy_report, commits, version)

    # Create GitHub Release
    print(f"Creating GitHub release {tag}...", file=sys.stderr)
    release_result = create_github_release(project_dir, tag, notes, args.dry_run)

    # Publish to npm
    print("Publishing to npm...", file=sys.stderr)
    npm_result = publish_npm(project_dir, args.dry_run)

    # Update changelog
    print("Updating changelog...", file=sys.stderr)
    changelog_result = update_changelog(project_dir, version, notes, args.dry_run)

    # Write reports
    if not args.dry_run:
        print(f"Writing publication report to {output_dir}...", file=sys.stderr)

    report = write_publication_report(
        output_dir, version, tag, deploy_report, release_result,
        npm_result, changelog_result, args.hitl_gate, hitl_passed, args.dry_run,
    )

    # Output machine-readable summary
    print(json.dumps(report))

    return 0 if report["status"] == "success" else 1


if __name__ == "__main__":
    sys.exit(main())