#!/usr/bin/env python3
"""
Faber Intent Wizard - Design System Applier

Invokes faber-design-system skill to get tokens and applies them to the generated project.
"""

import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Optional


def run_design_system(fixture: str, output_dir: Path, format: str = "all") -> Dict[str, Any]:
    """Run faber-design-system skill to generate tokens."""
    # Check if the skill exists first
    skill_path = Path(__file__).parent.parent.parent.parent / "skills" / "faber-design-system" / "scripts" / "design_system.py"
    if not skill_path.exists():
        print(f"  → Design system skill not found at {skill_path}, using fallback tokens")
        return {}

    cmd = [
        sys.executable,
        "-m", "skills.faber-design-system.scripts.design_system",
        "generate",
        "--fixture", fixture,
        "--output-dir", str(output_dir / "design-system-output"),
        "--format", format,
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=Path(__file__).parent.parent.parent.parent, timeout=30)
    except subprocess.TimeoutExpired:
        print(f"Warning: faber-design-system timed out after 30s, using fallback tokens", file=sys.stderr)
        return {}

    if result.returncode != 0:
        print(f"Warning: faber-design-system failed: {result.stderr}", file=sys.stderr)
        return {}

    # Read generated tokens
    tokens_file = output_dir / "design-system-output" / "design-tokens.json"
    if tokens_file.exists():
        with open(tokens_file, "r") as f:
            return json.load(f)

    return {}


def apply_tokens_to_astro_config(tokens: Dict[str, Any], astro_config_path: Path) -> None:
    """Update astro.config.mjs to import design system tokens."""
    if not astro_config_path.exists():
        return

    content = astro_config_path.read_text()

    # Add design system import if not present
    if "design-tokens.css" not in content:
        # Find the imports section and add design tokens import
        lines = content.split("\n")
        new_lines = []
        imports_added = False

        for line in lines:
            new_lines.append(line)
            if line.strip().startswith("import") and not imports_added:
                # Add after last import
                pass

        # Simpler approach: add to the top of the file if it has a specific pattern
        if "export default defineConfig" in content:
            # Insert import before export
            import_line = 'import "./src/styles/design-tokens.css";\n'
            content = content.replace(
                "export default defineConfig",
                import_line + "export default defineConfig"
            )
            astro_config_path.write_text(content)


def apply_tokens_to_global_css(tokens: Dict[str, Any], global_css_path: Path) -> None:
    """Update global.css to use design tokens."""
    if not global_css_path.exists():
        return

    # The design system already generates design-tokens.css which should be imported
    # This function ensures the import exists
    content = global_css_path.read_text()

    if "@import" not in content and "design-tokens" not in content:
        # Add import at the top
        import_line = '@import "./design-tokens.css";\n\n'
        global_css_path.write_text(import_line + content)


def generate_astro_design_tokens_css(tokens: Dict[str, Any], output_path: Path) -> None:
    """Generate design-tokens.css from tokens (fallback if design-system skill not available)."""
    # This is a simplified version - the real one comes from faber-design-system skill
    css = """/*
 * Faber Design Tokens - Generated by faber-intent-wizard
 * Fallback when faber-design-system skill is not available
 */

:root {
  /* Faber Brand Colors */
  --faber-primary: #2D7D46;
  --faber-primary-dark: #1e5c30;
  --faber-primary-light: #4ade80;
  --faber-secondary: #374151;
  --faber-accent: #f59e0b;

  /* Semantic Colors */
  --faber-success: #22c55e;
  --faber-warning: #f59e0b;
  --faber-danger: #ef4444;
  --faber-info: #3b82f6;

  /* Surface Colors */
  --faber-background: #ffffff;
  --faber-surface: #f9fafb;
  --faber-surface-hover: #f3f4f6;
  --faber-border: #e5e7eb;
  --faber-border-focus: #2D7D46;

  /* Text Colors */
  --faber-text: #111827;
  --faber-text-muted: #6b7280;
  --faber-text-light: #9ca3af;
  --faber-text-inverse: #ffffff;

  /* Gradients */
  --faber-gradient-primary: linear-gradient(135deg, #2D7D46 0%, #1e5c30 100%);
  --faber-gradient-hero: linear-gradient(135deg, #2D7D46 0%, #166534 50%, #14532d 100%);
  --faber-gradient-card: linear-gradient(180deg, #ffffff 0%, #f9fafb 100%);
  --faber-gradient-stats: linear-gradient(135deg, #2D7D46 0%, #059669 100%);

  /* Spacing */
  --faber-space-xs: 0.25rem;
  --faber-space-sm: 0.5rem;
  --faber-space-md: 1rem;
  --faber-space-lg: 1.5rem;
  --faber-space-xl: 2rem;
  --faber-space-2xl: 3rem;
  --faber-space-3xl: 4rem;

  /* Typography */
  --faber-font-sans: "Inter", system-ui, -apple-system, sans-serif;
  --faber-font-mono: "JetBrains Mono", "Fira Code", monospace;
  --faber-text-xs: 0.75rem;
  --faber-text-sm: 0.875rem;
  --faber-text-base: 1rem;
  --faber-text-lg: 1.125rem;
  --faber-text-xl: 1.25rem;
  --faber-text-2xl: 1.5rem;
  --faber-text-3xl: 1.875rem;
  --faber-text-4xl: 2.25rem;
  --faber-text-5xl: 3rem;
  --faber-text-6xl: 3.75rem;

  /* Border Radius */
  --faber-radius-sm: 0.25rem;
  --faber-radius-md: 0.375rem;
  --faber-radius-lg: 0.5rem;
  --faber-radius-xl: 0.75rem;
  --faber-radius-2xl: 1rem;
  --faber-radius-full: 9999px;

  /* Shadows */
  --faber-shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);
  --faber-shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
  --faber-shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  --faber-shadow-xl: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);

  /* Transitions */
  --faber-transition-fast: 150ms ease;
  --faber-transition-normal: 200ms ease;
  --faber-transition-slow: 300ms ease;

  /* Z-Index */
  --faber-z-dropdown: 100;
  --faber-z-sticky: 200;
  --faber-z-fixed: 300;
  --faber-z-modal-backdrop: 400;
  --faber-z-modal: 500;
  --faber-z-popover: 600;
  --faber-z-tooltip: 700;
}

/* Dark mode */
@media (prefers-color-scheme: dark) {
  :root {
    --faber-background: #0f172a;
    --faber-surface: #1e293b;
    --faber-surface-hover: #334155;
    --faber-border: #334155;
    --faber-text: #f1f5f9;
    --faber-text-muted: #94a3b8;
    --faber-text-light: #64748b;
  }
}

/* Utility classes using tokens */
.faber-gradient-primary { background-image: var(--faber-gradient-primary); }
.faber-gradient-hero { background-image: var(--faber-gradient-hero); }
.faber-gradient-card { background-image: var(--faber-gradient-card); }
.faber-gradient-stats { background-image: var(--faber-gradient-stats); }

.text-faber-primary { color: var(--faber-primary); }
.text-faber-text { color: var(--faber-text); }
.text-faber-text-muted { color: var(--faber-text-muted); }
.text-faber-danger { color: var(--faber-danger); }

.bg-faber-primary { background-color: var(--faber-primary); }
.bg-faber-surface { background-color: var(--faber-surface); }
.bg-faber-background { background-color: var(--faber-background); }
.bg-faber-danger { background-color: var(--faber-danger); }

.border-faber-border { border-color: var(--faber-border); }
.border-faber-primary { border-color: var(--faber-primary); }
.border-faber-danger { border-color: var(--faber-danger); }

.focus\\:ring-faber-primary:focus { --tw-ring-color: var(--faber-primary); }
.focus\\:ring-faber-primary\\/20:focus { --tw-ring-color: var(--faber-primary); --tw-ring-opacity: 0.2; }
.focus\\:ring-faber-danger:focus { --tw-ring-color: var(--faber-danger); }
.focus\\:ring-faber-danger\\/20:focus { --tw-ring-color: var(--faber-danger); --tw-ring-opacity: 0.2; }
.focus\\:border-faber-primary:focus { border-color: var(--faber-primary); }
.focus\\:border-faber-danger:focus { border-color: var(--faber-danger); }

.hover\\:bg-faber-primary-dark:hover { background-color: var(--faber-primary-dark); }
.hover\\:bg-faber-surface-hover:hover { background-color: var(--faber-surface-hover); }
.hover\\:text-faber-primary:hover { color: var(--faber-primary); }

.disabled\\:bg-faber-surface:disabled { background-color: var(--faber-surface); }
.disabled\\:cursor-not-allowed:disabled { cursor: not-allowed; }
.disabled\\:opacity-50:disabled { opacity: 0.5; }
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(css)


def apply_design_system(config: Dict[str, Any], output_dir: Path) -> None:
    """Main function to apply design system to generated project."""
    fixture = config.get("fixture", "faber-brand")

    # Try to run faber-design-system skill
    tokens = run_design_system(fixture, output_dir)

    # If skill not available or failed, generate fallback tokens
    if not tokens:
        print("  → Using fallback design tokens (faber-design-system skill not available)")
        tokens = {"fallback": True}

    # Generate design-tokens.css in src/styles
    styles_dir = output_dir / "src" / "styles"
    styles_dir.mkdir(parents=True, exist_ok=True)
    generate_astro_design_tokens_css(tokens, styles_dir / "design-tokens.css")

    # Update astro.config.mjs
    astro_config = output_dir / "astro.config.mjs"
    apply_tokens_to_astro_config(tokens, astro_config)

    # Update global.css if exists
    global_css = output_dir / "src" / "styles" / "global.css"
    if global_css.exists():
        apply_tokens_to_global_css(tokens, global_css)

    print(f"  ✓ Design system ({fixture}) applied to {output_dir}")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Apply design system to generated project")
    parser.add_argument("--fixture", default="faber-brand", help="Design system fixture")
    parser.add_argument("--output-dir", required=True, help="Output directory")

    args = parser.parse_args()

    config = {"fixture": args.fixture}
    apply_design_system(config, Path(args.output_dir))