#!/usr/bin/env python3
"""
Faber Intent Wizard - Intent Route Generator

Generates the Astro /intent page with multi-step wizard form
and the success confirmation page.
"""

import json
from typing import Any, Dict


# Wizard step definitions - matches intent-collect elicitation questions
WIZARD_STEPS = [
    {
        "id": "goal",
        "label": "Goal",
        "icon": "target",
        "fields": [
            {"name": "goal", "type": "textarea", "label": "What is the primary goal or outcome desired?", "required": True, "placeholder": "e.g., Build a marketing site for our bamboo supply chain platform..."}
        ]
    },
    {
        "id": "audience",
        "label": "Audience",
        "icon": "users",
        "fields": [
            {"name": "audience", "type": "textarea", "label": "Who are the primary audiences/users and their jobs-to-be-done?", "required": True, "placeholder": "e.g., Procurement managers at furniture brands who need traceable bamboo sourcing..."}
        ]
    },
    {
        "id": "non-goals",
        "label": "Non-Goals",
        "icon": "x-circle",
        "fields": [
            {"name": "non_goals", "type": "textarea", "label": "What is explicitly out of scope (non-goals)?", "required": False, "placeholder": "e.g., Mobile app, ERP integration, multi-language support..."}
        ]
    },
    {
        "id": "ia",
        "label": "Info Architecture",
        "icon": "layout",
        "fields": [
            {"name": "ia", "type": "textarea", "label": "What information architecture or content structure is needed?", "required": True, "placeholder": "e.g., Home, About, Products (with categories), Blog, Contact, Dashboard..."}
        ]
    },
    {
        "id": "content-model",
        "label": "Content Model",
        "icon": "database",
        "fields": [
            {"name": "content_model", "type": "textarea", "label": "What is the content model (types, fields, relationships)?", "required": True, "placeholder": "e.g., Product: name, description, specs[], certifications[], region. BlogPost: title, excerpt, content, tags[], author..."}
        ]
    },
    {
        "id": "constraints",
        "label": "Constraints",
        "icon": "shield",
        "fields": [
            {"name": "constraints", "type": "textarea", "label": "What constraints exist (brand, legal, technical, temporal)?", "required": False, "placeholder": "e.g., Must use brand green (#2D7D46), WCAG AA, GDPR compliant, launch by Q3..."}
        ]
    },
    {
        "id": "metrics",
        "label": "Success Metrics",
        "icon": "bar-chart",
        "fields": [
            {"name": "metrics", "type": "textarea", "label": "What are the success metrics or acceptance criteria?", "required": False, "placeholder": "e.g., 10k visits/mo, 5% contact form conversion, <3s load time, 99.9% uptime..."}
        ]
    },
]


def json_dumps(obj):
    return json.dumps(obj, separators=(',', ':'))


def generate_intent_page(config: Dict[str, Any]) -> str:
    """Generate the main /intent wizard page."""
    project_name = config["project_name"]
    fixture = config.get("fixture", "faber-brand")

    steps_json = json_dumps(WIZARD_STEPS)

    template = """---
// intent.astro - Multi-step Intent Wizard
// Generated by faber-intent-wizard for {project_name}
// Uses {fixture} design system tokens

import BaseLayout from "@/layouts/BaseLayout.astro";
import ProgressStepper from "@/components/ui/ProgressStepper.astro";
import Button from "@/components/ui/Button.astro";
import Card from "@/components/ui/Card.astro";
import {{ StepGoal, StepAudience, StepNonGoals, StepIA, StepContentModel, StepConstraints, StepMetrics, StepReview }} from "@/components/wizard";
---

<BaseLayout title="Start a Project | Faber Intent Wizard" description="Submit your project idea through our structured intent wizard. We'll generate a spec, trajectory, and scope baseline for your review.">

  <main class="min-h-screen bg-faber-background">
    <!-- Hero Section -->
    <section class="relative overflow-hidden bg-gradient-to-b from-faber-primary/5 via-transparent to-transparent py-16 md:py-24">
      <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div class="text-center">
          <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-faber-primary/10 text-faber-primary text-sm font-medium mb-6">
            <span class="relative flex h-2 w-2">
              <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-faber-primary opacity-75"></span>
              <span class="relative inline-flex rounded-full h-2 w-2 bg-faber-primary"></span>
            </span>
            Powered by Faber Framework
          </div>
          <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold text-faber-text tracking-tight mb-6">
            Start a Project
          </h1>
          <p class="text-lg md:text-xl text-faber-text-muted max-w-2xl mx-auto mb-10">
            Turn your idea into a structured spec with acceptance criteria, trajectory, and scope baseline —
            the Faber way. Our wizard guides you through 7 steps of structured elicitation.
          </p>
        </div>
      </div>
    </section>

    <!-- Wizard Form -->
    <section class="py-12 md:py-20 -mt-8 md:-mt-16 relative z-10">
      <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <!-- Progress Stepper -->
        <ProgressStepper
          steps={[
            { id: "goal", label: "Goal" },
            { id: "audience", label: "Audience" },
            { id: "non-goals", label: "Non-Goals" },
            { id: "ia", label: "Info Arch" },
            { id: "content-model", label: "Content Model" },
            { id: "constraints", label: "Constraints" },
            { id: "metrics", label: "Metrics" },
            { id: "review", label: "Review" }
          ]}
          currentStep={0}
          class="mb-10"
        />

        <!-- Wizard Form -->
        <form id="intent-wizard" class="space-y-8" method="POST" action="/api/intent">
          <input type="hidden" name="step" id="wizard-step" value="0" />
          <input type="hidden" name="production_context" value="normal" />

          <!-- Step Components (rendered conditionally via client-side JS) -->
          <StepGoal client:load />
          <StepAudience client:load />
          <StepNonGoals client:load />
          <StepIA client:load />
          <StepContentModel client:load />
          <StepConstraints client:load />
          <StepMetrics client:load />
          <StepReview client:load />

          <!-- Navigation -->
          <div class="flex items-center justify-between pt-4 border-t border-faber-border">
            <Button
              type="button"
              id="wizard-prev"
              variant="secondary"
              class="hidden"
              disabled
            >
              Previous
            </Button>
            <div class="flex gap-3">
              <Button
                type="button"
                id="wizard-next"
                variant="primary"
              >
                Next
              </Button>
              <Button
                type="submit"
                id="wizard-submit"
                variant="primary"
                class="hidden"
              >
                Submit Intent
              </Button>
            </div>
          </div>
        </form>
      </div>
    </section>

    <!-- Features/Trust Section -->
    <section class="py-16 bg-faber-surface/50">
      <div class="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <div class="grid md:grid-cols-3 gap-8">
          <Card title="Deterministic Specs" description="Same inputs always produce identical spec.md, trajectory.md, and scope-baseline.md artifacts.">
            <div class="text-4xl font-bold text-faber-primary">🔒</div>
          </Card>
          <Card title="Structured Elicitation" description="7-step wizard based on Faber's fixed question set — no gaps, no fabrication, only TODO: markers.">
            <div class="text-4xl font-bold text-faber-primary">📋</div>
          </Card>
          <Card title="Instant Pipeline" description="Submissions flow directly to D1, trigger Telegram alerts, and generate backlog drafts for the team.">
            <div class="text-4xl font-bold text-faber-primary">⚡</div>
          </Card>
        </div>
      </div>
    </section>
  </main>

  <script is:inline>
    // Wizard state management
    const steps = {steps_json};
    let currentStep = 0;
    const form = document.getElementById('intent-wizard');
    const stepInput = document.getElementById('wizard-step');
    const prevBtn = document.getElementById('wizard-prev');
    const nextBtn = document.getElementById('wizard-next');
    const submitBtn = document.getElementById('wizard-submit');

    const stepComponents = document.querySelectorAll('[data-wizard-step]');

    function showStep(stepIndex) {{
      stepComponents.forEach((el, idx) => {{
        el.style.display = idx === stepIndex ? 'block' : 'none';
        el.setAttribute('aria-hidden', idx !== stepIndex);
      }});

      currentStep = stepIndex;
      stepInput.value = stepIndex;

      // Update progress stepper (re-render or update)
      document.querySelectorAll('[data-stepper-step]').forEach((btn, idx) => {{
        btn.setAttribute('aria-current', idx === stepIndex ? 'step' : undefined);
        if (idx < stepIndex) {{
          btn.classList.remove('bg-faber-surface', 'border-faber-border', 'text-faber-text-muted');
          btn.classList.add('bg-faber-primary', 'text-white');
          btn.innerHTML = `<svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" /></svg>`;
        }} else if (idx === stepIndex) {{
          btn.classList.add('ring-4', 'ring-faber-primary/20');
        }} else {{
          btn.classList.remove('bg-faber-primary', 'text-white', 'ring-4', 'ring-faber-primary/20');
          btn.classList.add('bg-faber-surface', 'border-2', 'border-faber-border', 'text-faber-text-muted');
          btn.innerHTML = `<span>${{idx + 1}}</span>`;
        }}
        btn.disabled = idx > stepIndex;
      }});

      // Update nav buttons
      prevBtn.classList.toggle('hidden', stepIndex === 0);
      prevBtn.disabled = stepIndex === 0;
      nextBtn.classList.toggle('hidden', stepIndex === steps.length);
      submitBtn.classList.toggle('hidden', stepIndex !== steps.length);
    }}

    function validateStep(stepIndex) {{
      const step = steps[stepIndex];
      const component = stepComponents[stepIndex];
      const requiredFields = component.querySelectorAll('[required]');
      let valid = true;

      requiredFields.forEach(field => {{
        if (!field.value.trim()) {{
          field.classList.add('border-faber-danger', 'focus:border-faber-danger', 'focus:ring-faber-danger/20');
          field.classList.remove('border-faber-border', 'focus:border-faber-primary', 'focus:ring-faber-primary/20');
          valid = false;
        }} else {{
          field.classList.remove('border-faber-danger', 'focus:border-faber-danger', 'focus:ring-faber-danger/20');
          field.classList.add('border-faber-border', 'focus:border-faber-primary', 'focus:ring-faber-primary/20');
        }}
      }});

      return valid;
    }}

    nextBtn.addEventListener('click', () => {{
      if (validateStep(currentStep)) {{
        showStep(currentStep + 1);
      }}
    }});

    prevBtn.addEventListener('click', () => {{
      showStep(currentStep - 1);
    }});

    // Initialize
    showStep(0);
  </script>
</BaseLayout>
"""
    return template.format(project_name=project_name, fixture=fixture, steps_json=steps_json)


def generate_success_page(config: Dict[str, Any]) -> str:
    """Generate the success confirmation page."""
    project_name = config["project_name"]
    fixture = config.get("fixture", "faber-brand")

    template = """---
// success.astro - Intent Submission Success Page
// Generated by faber-intent-wizard for {project_name}
// Uses {fixture} design system tokens

import BaseLayout from "@/layouts/BaseLayout.astro";
import Card from "@/components/ui/Card.astro";
import Button from "@/components/ui/Button.astro";

interface Props {{
  intentId?: number
  specMd?: string
  trajectoryMd?: string
  scopeBaselineMd?: string
  backlogDraftMd?: string
}}

const {{ intentId, specMd, trajectoryMd, scopeBaselineMd, backlogDraftMd }} = Astro.props;
---

<BaseLayout title="Intent Submitted | Faber Intent Wizard" description="Your project intent has been submitted and processed.">

  <main class="min-h-screen bg-faber-background py-16 md:py-24">
    <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
      <!-- Success Header -->
      <div class="text-center mb-12">
        <div class="inline-flex items-center justify-center w-20 h-20 rounded-full bg-faber-primary/10 text-faber-primary mb-6">
          <svg class="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
          </svg>
        </div>
        <h1 class="text-3xl md:text-4xl font-bold text-faber-text mb-4">Intent Submitted Successfully</h1>
        <p class="text-lg text-faber-text-muted max-w-2xl mx-auto">
          Your project intent has been processed. Below are the generated artifacts — review them and share the scope baseline with your team.
        </p>
        {{intentId && <p class="mt-4 text-sm text-faber-text-muted">Intent ID: <code class="font-mono bg-faber-surface px-2 py-0.5 rounded">#{{intentId}}</code></p>}}
      </div>

      <!-- Artifact Tabs -->
      <div class="space-y-8">
        {{#if specMd}}
        <Card title="spec.md" description="Source of truth with IDed acceptance criteria (SPEC-NN)">
          <pre class="bg-faber-surface border border-faber-border rounded-lg p-4 overflow-x-auto text-sm text-faber-text"><code>{{specMd}}</code></pre>
          <div class="mt-4 flex gap-2">
            <Button variant="secondary" onclick="copyToClipboard('spec')">Copy</Button>
            <Button variant="ghost" onclick="downloadFile('spec.md', 'spec-md')">Download</Button>
          </div>
        </Card>
        {{/if}}

        {{#if trajectoryMd}}
        <Card title="trajectory.md" description="Expected path: ordered DAG of lifecycle steps + checkpoints + gates">
          <pre class="bg-faber-surface border border-faber-border rounded-lg p-4 overflow-x-auto text-sm text-faber-text"><code>{{trajectoryMd}}</code></pre>
          <div class="mt-4 flex gap-2">
            <Button variant="secondary" onclick="copyToClipboard('trajectory')">Copy</Button>
            <Button variant="ghost" onclick="downloadFile('trajectory.md', 'trajectory-md')">Download</Button>
          </div>
        </Card>
        {{/if}}

        {{#if scopeBaselineMd}}
        <Card title="scope-baseline.md" description="Plain-language, client-shareable scope definition — review with stakeholders">
          <pre class="bg-faber-surface border border-faber-border rounded-lg p-4 overflow-x-auto text-sm text-faber-text"><code>{{scopeBaselineMd}}</code></pre>
          <div class="mt-4 flex gap-2">
            <Button variant="secondary" onclick="copyToClipboard('scope')">Copy</Button>
            <Button variant="ghost" onclick="downloadFile('scope-baseline.md', 'scope-md')">Download</Button>
          </div>
        </Card>
        {{/if}}

        {{#if backlogDraftMd}}
        <Card title="Backlog Draft" description="GitHub issue-ready backlog items generated from your intent">
          <pre class="bg-faber-surface border border-faber-border rounded-lg p-4 overflow-x-auto text-sm text-faber-text"><code>{{backlogDraftMd}}</code></pre>
          <div class="mt-4 flex gap-2">
            <Button variant="secondary" onclick="copyToClipboard('backlog')">Copy</Button>
            <Button variant="ghost" onclick="downloadFile('backlog-draft.md', 'backlog-md')">Download</Button>
          </div>
        </Card>
        {{/if}}
      </div>

      <!-- Next Steps -->
      <div class="mt-12 p-6 bg-faber-primary/5 border border-faber-primary/20 rounded-xl">
        <h3 class="text-lg font-semibold text-faber-primary mb-4">What happens next?</h3>
        <ol class="space-y-2 text-faber-text text-sm">
          <li class="flex items-start gap-3"><span class="flex-shrink-0 w-6 h-6 rounded-full bg-faber-primary text-white text-xs font-bold flex items-center justify-center">1</span> Our team reviews your intent within 24 hours</li>
          <li class="flex items-start gap-3"><span class="flex-shrink-0 w-6 h-6 rounded-full bg-faber-primary text-white text-xs font-bold flex items-center justify-center">2</span> We'll reach out via Telegram/email to confirm scope baseline</li>
          <li class="flex items-start gap-3"><span class="flex-shrink-0 w-6 h-6 rounded-full bg-faber-primary text-white text-xs font-bold flex items-center justify-center">3</span> Upon confirmation, the project enters the Faber lifecycle (scaffold → build → deploy)</li>
          <li class="flex items-start gap-3"><span class="flex-shrink-0 w-6 h-6 rounded-full bg-faber-primary text-white text-xs font-bold flex items-center justify-center">4</span> You'll receive updates at each lifecycle stage</li>
        </ol>
      </div>

      <!-- CTA -->
      <div class="mt-10 text-center">
        <Button variant="primary" href="/intent" class="mr-4">Submit Another Intent</Button>
        <Button variant="secondary" href="/">Back to Home</Button>
      </div>
    </div>
  </main>

  <script is:inline>
    function copyToClipboard(type) {{
      const selectors = {{
        spec: 'pre code',
        trajectory: 'pre code',
        scope: 'pre code',
        backlog: 'pre code'
      }};
      const text = document.querySelector(selectors[type])?.textContent || '';
      navigator.clipboard.writeText(text).then(() => {{
        alert('Copied to clipboard!');
      }});
    }}

    function downloadFile(filename, elementId) {{
      const text = document.getElementById(elementId)?.textContent || '';
      const blob = new Blob([text], {{ type: 'text/markdown' }});
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
    }}
  </script>
</BaseLayout>
"""
    return template.format(project_name=project_name, fixture=fixture)


def generate_wizard_components(config: Dict[str, Any]) -> Dict[str, str]:
    """Generate individual wizard step components."""
    project_name = config["project_name"]
    fixture = config.get("fixture", "faber-brand")

    components = {}

    # Step Goal
    components["StepGoal.astro"] = """---
// StepGoal.astro - Wizard Step 1: Goal
// Generated by faber-intent-wizard for {project_name}

import Textarea from "@/components/ui/Textarea.astro";
---

<div data-wizard-step="0" class="space-y-6">
  <div>
    <h2 class="text-2xl font-bold text-faber-text mb-2">What's the primary goal?</h2>
    <p class="text-faber-text-muted">Describe the main outcome you want to achieve.</p>
  </div>

  <Textarea
    name="goal"
    label="Primary Goal"
    placeholder="e.g., Build a marketing site for our bamboo supply chain platform that showcases our ESG credentials and generates qualified leads..."
    required
    rows={4}
  />

  <div class="p-4 bg-faber-primary/5 border border-faber-primary/20 rounded-lg">
    <p class="text-sm text-faber-primary"><strong>Tip:</strong> Be specific about the outcome. "Increase sales" → "Generate 50 qualified pipeline opportunities per quarter from furniture procurement managers."</p>
  </div>
</div>
""".format(project_name=project_name)

    # Step Audience
    components["StepAudience.astro"] = """---
// StepAudience.astro - Wizard Step 2: Audience
// Generated by faber-intent-wizard for {project_name}

import Textarea from "@/components/ui/Textarea.astro";
---

<div data-wizard-step="1" class="space-y-6" style="display: none;">
  <div>
    <h2 class="text-2xl font-bold text-faber-text mb-2">Who is this for?</h2>
    <p class="text-faber-text-muted">Describe your primary audiences and their jobs-to-be-done.</p>
  </div>

  <Textarea
    name="audience"
    label="Target Audience & Jobs-to-be-Done"
    placeholder="e.g., Primary: Procurement managers at mid-market furniture brands (jobs: source sustainable materials, verify ESG claims, reduce supply chain risk). Secondary: Sustainability officers, C-suite..."
    required
    rows={5}
  />

  <div class="p-4 bg-faber-primary/5 border border-faber-primary/20 rounded-lg">
    <p class="text-sm text-faber-primary"><strong>Tip:</strong> Include roles, industries, company sizes, and what they're trying to accomplish (JTBD framework).</p>
  </div>
</div>
""".format(project_name=project_name)

    # Step Non-Goals
    components["StepNonGoals.astro"] = """---
// StepNonGoals.astro - Wizard Step 3: Non-Goals
// Generated by faber-intent-wizard for {project_name}

import Textarea from "@/components/ui/Textarea.astro";
---

<div data-wizard-step="2" class="space-y-6" style="display: none;">
  <div>
    <h2 class="text-2xl font-bold text-faber-text mb-2">What's explicitly out of scope?</h2>
    <p class="text-faber-text-muted">Define boundaries to prevent scope creep.</p>
  </div>

  <Textarea
    name="non_goals"
    label="Non-Goals (Optional)"
    placeholder="e.g., Mobile app, ERP integration, multi-language support, user authentication system, payment processing, real-time chat..."
    required={false}
    rows={4}
  />

  <div class="p-4 bg-faber-primary/5 border border-faber-primary/20 rounded-lg">
    <p class="text-sm text-faber-primary"><strong>Tip:</strong> Being explicit about what you're NOT building is as important as what you ARE building.</p>
  </div>
</div>
""".format(project_name=project_name)

    # Step IA
    components["StepIA.astro"] = """---
// StepIA.astro - Wizard Step 4: Information Architecture
// Generated by faber-intent-wizard for {project_name}

import Textarea from "@/components/ui/Textarea.astro";
---

<div data-wizard-step="3" class="space-y-6" style="display: none;">
  <div>
    <h2 class="text-2xl font-bold text-faber-text mb-2">What's the site structure?</h2>
    <p class="text-faber-text-muted">List pages, sections, and navigation hierarchy.</p>
  </div>

  <Textarea
    name="ia"
    label="Information Architecture"
    placeholder="e.g., Home (hero, value props, trust signals), About (mission, team, certifications), Products (category grid, detail pages, comparison), Resources (blog, case studies, whitepapers), Contact (form, locations, FAQ), Dashboard (client portal)..."
    required
    rows={5}
  />

  <div class="p-4 bg-faber-primary/5 border border-faber-primary/20 rounded-lg">
    <p class="text-sm text-faber-primary"><strong>Tip:</strong> Use format: Page Name (key sections). Think about user flows, not just pages.</p>
  </div>
</div>
""".format(project_name=project_name)

    # Step Content Model
    components["StepContentModel.astro"] = """---
// StepContentModel.astro - Wizard Step 5: Content Model
// Generated by faber-intent-wizard for {project_name}

import Textarea from "@/components/ui/Textarea.astro";
---

<div data-wizard-step="4" class="space-y-6" style="display: none;">
  <div>
    <h2 class="text-2xl font-bold text-faber-text mb-2">What content types do you need?</h2>
    <p class="text-faber-text-muted">Define content types, fields, and relationships.</p>
  </div>

  <Textarea
    name="content_model"
    label="Content Model"
    placeholder="e.g., Product: name, slug, description, specs[], certifications[], region, sustainabilityScore. CaseStudy: title, client, challenge, solution, results[], metrics[]. BlogPost: title, excerpt, content, tags[], author, publishedAt..."
    required
    rows={5}
  />

  <div class="p-4 bg-faber-primary/5 border border-faber-primary/20 rounded-lg">
    <p class="text-sm text-faber-primary"><strong>Tip:</strong> Format: TypeName: field1, field2[], field3. Use [] for arrays, specify relationships.</p>
  </div>
</div>
""".format(project_name=project_name)

    # Step Constraints
    components["StepConstraints.astro"] = """---
// StepConstraints.astro - Wizard Step 6: Constraints
// Generated by faber-intent-wizard for {project_name}

import Textarea from "@/components/ui/Textarea.astro";
---

<div data-wizard-step="5" class="space-y-6" style="display: none;">
  <div>
    <h2 class="text-2xl font-bold text-faber-text mb-2">What constraints exist?</h2>
    <p class="text-faber-text-muted">Brand, legal, technical, and temporal boundaries.</p>
  </div>

  <Textarea
    name="constraints"
    label="Constraints (Optional)"
    placeholder="e.g., Brand: must use #2D7D46 primary, Inter font. Legal: GDPR, CCPA compliant. Technical: Astro + Cloudflare Pages, <3s LCP. Temporal: MVP by Sep 1, Phase 2 by Dec 1. Budget: $50k..."
    required={false}
    rows={5}
  />

  <div class="p-4 bg-faber-primary/5 border border-faber-primary/20 rounded-lg">
    <p class="text-sm text-faber-primary"><strong>Tip:</strong> Categorize: Brand / Legal / Technical / Temporal / Budget. More constraints = better estimates.</p>
  </div>
</div>
""".format(project_name=project_name)

    # Step Metrics
    components["StepMetrics.astro"] = """---
// StepMetrics.astro - Wizard Step 7: Success Metrics
// Generated by faber-intent-wizard for {project_name}

import Textarea from "@/components/ui/Textarea.astro";
---

<div data-wizard-step="6" class="space-y-6" style="display: none;">
  <div>
    <h2 class="text-2xl font-bold text-faber-text mb-2">How will you measure success?</h2>
    <p class="text-faber-text-muted">Define quantitative acceptance criteria.</p>
  </div>

  <Textarea
    name="metrics"
    label="Success Metrics (Optional)"
    placeholder="e.g., Traffic: 10k visits/mo by month 6. Conversion: 5% contact form → qualified lead. Performance: <3s LCP, 90+ Lighthouse. Business: $500k pipeline influenced in year 1. SEO: Top 3 for 'sustainable bamboo sourcing'..."
    required={false}
    rows={5}
  />

  <div class="p-4 bg-faber-primary/5 border border-faber-primary/20 rounded-lg">
    <p class="text-sm text-faber-primary"><strong>Tip:</strong> Use SMART criteria: Specific, Measurable, Achievable, Relevant, Time-bound.</p>
  </div>
</div>
""".format(project_name=project_name)

    # Step Review
    components["StepReview.astro"] = """---
// StepReview.astro - Wizard Step 8: Review & Submit
// Generated by faber-intent-wizard for {project_name}

import Card from "@/components/ui/Card.astro";
---

<div data-wizard-step="7" class="space-y-6" style="display: none;">
  <div>
    <h2 class="text-2xl font-bold text-faber-text mb-2">Review Your Intent</h2>
    <p class="text-faber-text-muted">Confirm everything looks correct before submitting.</p>
  </div>

  <div id="review-summary" class="space-y-4">
    <!-- Populated by client-side JS -->
    <div class="text-center py-8 text-faber-text-muted">
      <svg class="mx-auto h-8 w-8 animate-spin text-faber-primary" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
      <p class="mt-2">Generating summary...</p>
    </div>
  </div>

  <div class="p-4 bg-faber-surface border border-faber-border rounded-lg">
    <h4 class="font-medium text-faber-text mb-2">By submitting, you agree to:</h4>
    <ul class="text-sm text-faber-text-muted space-y-1">
      <li>• Faber Framework processing your intent per our privacy policy</li>
      <li>• Receiving Telegram/email updates on your project status</li>
      <li>• Scope baseline confirmation before work begins (HITL gate)</li>
    </ul>
  </div>
</div>
""".format(project_name=project_name)

    return components


if __name__ == "__main__":
    print("Use via generate_wizard.py")