#!/usr/bin/env python3
"""
Faber Intent Wizard - D1 Schema Generator

Generates D1 SQL schema for the `intents` table.
"""

from typing import Any, Dict, List


def generate_d1_schema() -> str:
    """Generate complete D1 schema SQL for intents table."""
    return """-- Faber Intent Wizard D1 Schema
-- Generated by faber-intent-wizard skill
-- Stores project intent submissions with full artifact history

-- Intents table (core submission storage)
CREATE TABLE IF NOT EXISTS intents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_context TEXT NOT NULL,
  production_context TEXT NOT NULL DEFAULT 'normal',
  spec_md TEXT,
  trajectory_md TEXT,
  scope_baseline_md TEXT,
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'processing', 'completed', 'archived')),
  extracted_facts TEXT, -- JSON
  elicited_gaps TEXT,   -- JSON
  backlog_draft_md TEXT,
  telegram_notified INTEGER NOT NULL DEFAULT 0,
  telegram_message_id INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_intents_status ON intents(status);
CREATE INDEX IF NOT EXISTS idx_intents_created_at ON intents(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_intents_production_context ON intents(production_context);
CREATE INDEX IF NOT EXISTS idx_intents_telegram_notified ON intents(telegram_notified);

-- Trigger to auto-update updated_at
CREATE TRIGGER IF NOT EXISTS trigger_intents_updated_at
AFTER UPDATE ON intents
BEGIN
  UPDATE intents SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- View for public-facing intent summaries (excludes sensitive data)
CREATE VIEW IF NOT EXISTS intent_summaries AS
SELECT
  id,
  production_context,
  status,
  json_extract(extracted_facts, '$.goal') as goal,
  json_extract(extracted_facts, '$.audience') as audience,
  created_at
FROM intents
WHERE status IN ('completed', 'archived')
ORDER BY created_at DESC;
"""


def generate_migration_sql() -> str:
    """Generate initial migration SQL."""
    return f"""-- Migration: 0001_initial_schema
-- Generated by faber-intent-wizard skill

{generate_d1_schema()}

-- Verify schema
SELECT name FROM sqlite_master WHERE type='table' AND name='intents';
SELECT name FROM sqlite_master WHERE type='index' AND name LIKE 'idx_intents_%';
SELECT name FROM sqlite_master WHERE type='view' AND name='intent_summaries';
SELECT sql FROM sqlite_master WHERE type='trigger' AND name='trigger_intents_updated_at';
"""


if __name__ == "__main__":
    print(generate_d1_schema())