#!/usr/bin/env python3
"""
Faber Intent Wizard - API & Telegram Generator

Generates the POST /api/intent endpoint (stores to D1, emits artifacts, notifies Telegram)
and the Telegram webhook handler.
"""

from typing import Any, Dict


def generate_intent_api(config: Dict[str, Any]) -> str:
    """Generate the POST /api/intent API endpoint."""
    project_name = config["project_name"]
    fixture = config.get("fixture", "faber-brand")
    telegram_bot_token = config.get("telegram", {}).get("bot_token", "<your-telegram-bot-token>")
    telegram_chat_id = config.get("telegram", {}).get("chat_id", "<your-telegram-chat-id>")

    template = """// api/intent.ts - POST /api/intent endpoint
// Generated by faber-intent-wizard for {project_name}
// Stores submission to D1, emits artifacts via intent-collect logic, notifies Telegram

import type {{ APIRoute }} from "astro";
import {{ drizzle }} from "drizzle-orm/d1";
import {{ intents }} from "@/db/schema";
import {{ eq }} from "drizzle-orm";
import {{ z }} from "zod";

// Input validation schema
const IntentSchema = z.object({{
  goal: z.string().min(10, "Goal must be at least 10 characters"),
  audience: z.string().min(10, "Audience must be at least 10 characters"),
  non_goals: z.string().optional().default(""),
  ia: z.string().min(10, "Information architecture must be at least 10 characters"),
  content_model: z.string().min(10, "Content model must be at least 10 characters"),
  constraints: z.string().optional().default(""),
  metrics: z.string().optional().default(""),
  production_context: z.enum(["prototype", "normal", "client-production"]).default("normal"),
}});

// Telegram notification payload
interface TelegramPayload {{
  chat_id: string;
  text: string;
  parse_mode: "Markdown";
}}

// Build client context from form data
function buildClientContext(data: z.infer<typeof IntentSchema>): string {{
  return `Goal: ${{data.goal}}
Audience: ${{data.audience}}
${{data.non_goals ? `Non-Goals: ${{data.non_goals}}` : ""}}
Information Architecture: ${{data.ia}}
Content Model: ${{data.content_model}}
${{data.constraints ? `Constraints: ${{data.constraints}}` : ""}}
${{data.metrics ? `Success Metrics: ${{data.metrics}}` : ""}}`;
}}

// Extract facts from client context (mirrors intent-collect logic)
function extractFacts(clientContext: string): Record<string, string> {{
  const facts: Record<string, string> = {{}};
  const ctxLower = clientContext.toLowerCase();

  // Goal extraction
  const goalMatch = clientContext.match(/Goal:\\s*([^\\n]+)/i);
  if (goalMatch) facts.goal = goalMatch[1].trim();

  // Audience extraction
  const audienceMatch = clientContext.match(/Audience:\\s*([^\\n]+)/i);
  if (audienceMatch) facts.audience = audienceMatch[1].trim();

  // Constraints extraction
  const constraintsMatch = clientContext.match(/Constraints:\\s*([^\\n]+)/i);
  if (constraintsMatch) facts.constraints = constraintsMatch[1].trim();

  return facts;
}}

// Elicit gaps via fixed question set (mirrors intent-collect logic)
function elicitGaps(clientContext: string, facts: Record<string, string>): string[] {{
  const gaps: string[] = [];
  const ctxLower = clientContext.toLowerCase();

  const questions = [
    "What is the primary goal or outcome desired?",
    "Who are the primary audiences/users and their jobs-to-be-done?",
    "What is explicitly out of scope (non-goals)?",
    "What information architecture or content structure is needed?",
    "What is the content model (types, fields, relationships)?",
    "What constraints exist (brand, legal, technical, temporal)?",
    "What are the success metrics or acceptance criteria?",
  ];

  const keywords = [
    ["goal", "objective"],
    ["audience", "user", "jobs"],
    ["non-goal", "scope", "out of scope"],
    ["architecture", "structure", "navigation"],
    ["model", "type", "field", "relationship"],
    ["constraint", "limit", "brand", "legal", "technical"],
    ["metric", "success", "criteria", "kpi"],
  ];

  for (let i = 0; i < questions.length; i++) {{
    if (!keywords[i].some(k => ctxLower.includes(k))) {{
      gaps.push(`${{i + 1}}. ${{questions[i]}}`);
    }}
  }}

  return gaps;
}}

// Generate spec.md (mirrors intent-collect logic)
function generateSpec(clientContext: string, facts: Record<string, string>, gaps: string[]): string {{
  const goal = facts.goal || "Build a website";
  const audience = facts.audience || "Target audience";
  const constraints = facts.constraints || "Brand guidelines";

  let spec = `# Spec

## Context
${{clientContext}}
- Goal: ${{goal}}
- Audience: ${{audience}}
- Non-goals: ${{data.non_goals || "None specified"}}
- Constraints: ${{constraints}}

## Acceptance Criteria

- SPEC-01: The system shall support the primary goal: ${{goal}}
- SPEC-02: The system shall serve the target audience: ${{audience}}
`;

  if (clientContext.toLowerCase().includes("blog") || clientContext.toLowerCase().includes("cms")) {{
    spec += `- SPEC-03: Content shall be editable via admin interface\\n`;
    spec += `- SPEC-04: Content shall support versioning\\n`;
  }} else if (clientContext.toLowerCase().includes("ecommerce") || clientContext.toLowerCase().includes("shop")) {{
    spec += `- SPEC-03: Product catalog shall support search and filtering\\n`;
    spec += `- SPEC-04: Checkout process shall be PCI compliant\\n`;
  }} else {{
    spec += `- SPEC-03: System shall be responsive and accessible\\n`;
    spec += `- SPEC-04: System shall follow security best practices\\n`;
  }}

  if (gaps.length > 0) {{
    spec += `\\n## TODO (Elicited Gaps)\\n`;
    gaps.forEach(gap => {{ spec += `- TODO: ${{gap}}\\n`; }});
  }}

  return spec;
}}

// Generate trajectory.md (mirrors intent-collect logic)
function generateTrajectory(productionContext: string): string {{
  const strictnessMap: Record<string, string> = {{
    prototype: "partial",
    normal: "ordered",
    "client-production": "exact",
  }};
  const strictness = strictnessMap[productionContext] || "ordered";

  const lifecycleStages = [
    "intent-collect",
    "scaffold",
    "build",
    "evaluate",
    "deploy",
    "publish",
    "observe",
    "feedback",
  ];

  const trajectorySteps = lifecycleStages.map((stage, idx) => `${{idx + 1}}. ${{stage}}`);
  trajectorySteps.push(`${{lifecycleStages.length + 1}}. HITL confirmation`);

  return `# Trajectory (strictness: ${{strictness}})

${{trajectorySteps.join("\\n")}}
`;
}}

// Generate scope-baseline.md (mirrors intent-collect logic)
function generateScopeBaseline(clientContext: string, facts: Record<string, string>): string {{
  const goal = facts.goal || "Build a website";
  const audience = facts.audience || "Target audience";
  const constraints = facts.constraints || "Brand guidelines";

  return `# Scope Baseline

Derived from the provided context.

${{clientContext}}
- Goal: ${{goal}}
- Audience: ${{audience}}
- Non-goals: ${{data.non_goals || "None specified"}}
- Constraints: ${{constraints}}

TODO: Review with client.
`;
}}

// Generate backlog draft markdown
function generateBacklogDraft(clientContext: string, facts: Record<string, string>, spec: string): string {{
  const goal = facts.goal || "Build a website";

  return `# Backlog Draft — Generated from Intent #${{Date.now()}}

*Auto-generated from intent submission. Review and refine before adding to project backlog.*

## Epic: ${{goal}}

### Functional Requirements
- [ ] Implement core functionality for: ${{goal}}
- [ ] Support target audience: ${{facts.audience || "TBD"}}
- [ ] Meet constraints: ${{facts.constraints || "TBD"}}

### Technical Requirements
- [ ] Astro + Cloudflare Pages setup
- [ ] D1 database schema for content
- [ ] CI/CD pipeline (lint → test → deploy-preview → deploy-staging → deploy-production)
- [ ] Design system integration ({fixture} fixture)

### Acceptance Criteria (from spec)
${{spec.split("\\n").filter(l => l.trim().startsWith("- SPEC-")).map(l => `- [ ] ${{l.replace("- SPEC-", "SPEC-")}}`).join("\\n")}}

### Open Questions (from elicited gaps)
${{spec.includes("TODO (Elicited Gaps)") ? spec.split("TODO (Elicited Gaps)")[1].split("\\n").filter(l => l.trim().startsWith("- TODO:")).map(l => `- [ ] ${{l.replace("- TODO:", "").trim()}}`).join("\\n") : "- [ ] No elicited gaps"}}

---
*Generated by Faber Intent Wizard on ${{new Date().toISOString()}}*
`;
}}

// Send Telegram notification
async function sendTelegramNotification(
  botToken: string,
  chatId: string,
  intentId: number,
  scopeBaseline: string,
  clientContext: string
): Promise<{{ success: boolean; messageId?: number; error?: string }}> {{
  const message = `🎯 *New Intent Submitted* (#${{intentId}})

*Goal:* ${{clientContext.split("\\n")[0].replace("Goal: ", "")}}

*Scope Baseline Preview:*
\`\`\`
${{scopeBaseline.substring(0, 800)}${{scopeBaseline.length > 800 ? "..." : ""}}
\`\`\`

[View in Admin](/admin/intents/${{intentId}})`;

  const payload: TelegramPayload = {{
    chat_id: chatId,
    text: message,
    parse_mode: "Markdown",
  }};

  try {{
    const response = await fetch(`https://api.telegram.org/bot${{botToken}}/sendMessage`, {{
      method: "POST",
      headers: {{ "Content-Type": "application/json" }},
      body: JSON.stringify(payload),
    }});

    const result = await response.json();
    if (result.ok) {{
      return {{ success: true, messageId: result.result.message_id }};
    }}
    return {{ success: false, error: result.description }};
  }} catch (err) {{
    return {{ success: false, error: String(err) }};
  }}
}}

export const POST: APIRoute = async ({{ request, locals }}) => {{
  try {{
    // Parse and validate input
    const formData = await request.formData();
    const rawData = Object.fromEntries(formData.entries());

    const parseResult = IntentSchema.safeParse(rawData);
    if (!parseResult.success) {{
      return new Response(JSON.stringify({{
        error: "Validation failed",
        details: parseResult.error.flatten().fieldErrors,
      }}), {{ status: 400, headers: {{ "Content-Type": "application/json" }} }});
    }}

    const data = parseResult.data;
    const clientContext = buildClientContext(data);

    // Process through intent-collect pipeline
    const facts = extractFacts(clientContext);
    const gaps = elicitGaps(clientContext, facts);
    const specMd = generateSpec(clientContext, facts, gaps);
    const trajectoryMd = generateTrajectory(data.production_context);
    const scopeBaselineMd = generateScopeBaseline(clientContext, facts);
    const backlogDraftMd = generateBacklogDraft(clientContext, facts, specMd);

    // Store in D1
    const db = drizzle(locals.runtime.env.DB);
    const [inserted] = await db.insert(intents).values({{
      clientContext,
      productionContext: data.production_context,
      specMd,
      trajectoryMd,
      scopeBaselineMd,
      extractedFacts: JSON.stringify(facts),
      elicitedGaps: JSON.stringify(gaps),
      backlogDraftMd,
      status: "completed",
    }}).returning({{ id: intents.id }});

    const intentId = inserted.id;

    // Send Telegram notification (non-blocking)
    const telegramResult = await sendTelegramNotification(
      "{telegram_bot_token}",
      "{telegram_chat_id}",
      intentId,
      scopeBaselineMd,
      clientContext
    );

    // Update telegram notification status
    if (telegramResult.success) {{
      await db.update(intents)
        .set({{ telegramNotified: 1, telegramMessageId: telegramResult.messageId }})
        .where(eq(intents.id, intentId));
    }}

    // Redirect to success page with artifacts
    const successUrl = `/intent/success?id=${{intentId}}`;
    return new Response(null, {{
      status: 302,
      headers: {{ Location: successUrl }},
    }});

  }} catch (err) {{
    console.error("Intent submission error:", err);
    return new Response(JSON.stringify({{
      error: "Internal server error",
      message: String(err),
    }}), {{ status: 500, headers: {{ "Content-Type": "application/json" }} }});
  }}
}};
"""

    return template.format(
        project_name=project_name,
        fixture=fixture,
        telegram_bot_token=telegram_bot_token,
        telegram_chat_id=telegram_chat_id,
    )


def generate_telegram_webhook(config: Dict[str, Any]) -> str:
    """Generate the Telegram webhook handler."""
    project_name = config["project_name"]
    telegram_bot_token = config.get("telegram", {}).get("bot_token", "<your-telegram-bot-token>")

    template = """// api/telegram.ts - Telegram webhook handler
// Generated by faber-intent-wizard for {project_name}
// Handles incoming Telegram updates (commands, messages, callbacks)

import type {{ APIRoute }} from "astro";
import {{ drizzle }} from "drizzle-orm/d1";
import {{ intents }} from "@/db/schema";
import {{ eq, desc }} from "drizzle-orm";

// Telegram types
interface TelegramUpdate {{
  update_id: number;
  message?: TelegramMessage;
  callback_query?: TelegramCallbackQuery;
}}

interface TelegramMessage {{
  message_id: number;
  from: TelegramUser;
  chat: TelegramChat;
  date: number;
  text?: string;
  entities?: TelegramEntity[];
}}

interface TelegramUser {{
  id: number;
  is_bot: boolean;
  first_name: string;
  username?: string;
}}

interface TelegramChat {{
  id: number;
  type: "private" | "group" | "supergroup" | "channel";
  username?: string;
}}

interface TelegramCallbackQuery {{
  id: string;
  from: TelegramUser;
  message?: TelegramMessage;
  data?: string;
}}

interface TelegramEntity {{
  type: string;
  offset: number;
  length: number;
}}

// Verify webhook secret (optional but recommended)
function verifyWebhookSecret(request: Request, secret: string): boolean {{
  const header = request.headers.get("X-Telegram-Bot-Api-Secret-Token");
  return header === secret;
}}

export const POST: APIRoute = async ({{ request, locals }}) => {{
  try {{
    // Verify secret if configured
    const webhookSecret = locals.runtime.env.TELEGRAM_WEBHOOK_SECRET;
    if (webhookSecret && !verifyWebhookSecret(request, webhookSecret)) {{
      return new Response("Unauthorized", {{ status: 401 }});
    }}

    const update: TelegramUpdate = await request.json();

    // Handle message
    if (update.message) {{
      await handleMessage(update.message, locals);
    }}

    // Handle callback query
    if (update.callback_query) {{
      await handleCallbackQuery(update.callback_query, locals);
    }}

    return new Response("OK", {{ status: 200 }});

  }} catch (err) {{
    console.error("Telegram webhook error:", err);
    return new Response("Internal Server Error", {{ status: 500 }});
  }}
}};

async function handleMessage(message: TelegramMessage, locals: any) {{
  const chatId = message.chat.id.toString();
  const text = message.text || "";
  const userId = message.from.id;

  // Only respond to configured chat (or allow all in dev)
  const allowedChatId = locals.runtime.env.TELEGRAM_CHAT_ID;
  if (allowedChatId && chatId !== allowedChatId) {{
    console.log(`Ignoring message from unauthorized chat: ${{chatId}}`);
    return;
  }}

  const db = drizzle(locals.runtime.env.DB);

  // Commands
  if (text.startsWith("/")) {{
    const [command] = text.split(" ");

    switch (command) {{
      case "/start":
      case "/help":
        await sendTelegramMessage(locals, chatId, `🤖 *Faber Intent Wizard Bot*

Commands:
/start - Show this help
/help - Show this help
/list - List recent intents
/status <id> - Check intent status
/summary <id> - Show intent summary`);

        break;

      case "/list":
        const recentIntents = await db.select()
          .from(intents)
          .orderBy(desc(intents.createdAt))
          .limit(10)
          .all();

        if (recentIntents.length === 0) {{
          await sendTelegramMessage(locals, chatId, "No intents found.");
        }} else {{
          const list = recentIntents.map((i, idx) =>
            `${{idx + 1}}. #${{i.id}} - ${{i.clientContext.split("\\n")[0]?.substring(0, 60)}}... (${{i.status}})`
          ).join("\\n");
          await sendTelegramMessage(locals, chatId, `📋 *Recent Intents*\\n${{list}}`);
        }}
        break;

      case "/status":
        const statusId = parseInt(text.replace("/status", "").trim());
        if (isNaN(statusId)) {{
          await sendTelegramMessage(locals, chatId, "Usage: /status <intent-id>");
        }} else {{
          const intent = await db.select().from(intents).where(eq(intents.id, statusId)).get();
          if (!intent) {{
            await sendTelegramMessage(locals, chatId, `Intent #${{statusId}} not found.`);
          }} else {{
            await sendTelegramMessage(locals, chatId,
              `📊 *Intent #${{intent.id}} Status*\\n` +
              `Status: ${{intent.status}}\\n` +
              `Created: ${{new Date(intent.createdAt).toLocaleString()}}\\n` +
              `Production Context: ${{intent.productionContext}}\\n` +
              `Telegram Notified: ${{intent.telegramNotified ? "✅" : "❌"}}`
            );
          }}
        }}
        break;

      case "/summary":
        const summaryId = parseInt(text.replace("/summary", "").trim());
        if (isNaN(summaryId)) {{
          await sendTelegramMessage(locals, chatId, "Usage: /summary <intent-id>");
        }} else {{
          const intent = await db.select().from(intents).where(eq(intents.id, summaryId)).get();
          if (!intent) {{
            await sendTelegramMessage(locals, chatId, `Intent #${{summaryId}} not found.`);
          }} else {{
            await sendTelegramMessage(locals, chatId,
              `📄 *Intent #${{intent.id}} Scope Baseline*\\n\`\`\`${{intent.scopeBaselineMd?.substring(0, 3000) || "N/A"}}\`\`\``
            );
          }}
        }}
        break;

      default:
        await sendTelegramMessage(locals, chatId, `Unknown command: ${{command}}. Use /help for available commands.`);
    }}
  }}
}}

async function handleCallbackQuery(query: TelegramCallbackQuery, locals: any) {{
  // Handle inline keyboard callbacks if needed
  console.log("Callback query:", query.data);
  // Could add actions like "approve", "reject", "request-changes" for scope baseline
}}

async function sendTelegramMessage(locals: any, chatId: string, text: string) {{
  const botToken = locals.runtime.env.TELEGRAM_BOT_TOKEN;
  if (!botToken || botToken === "<your-telegram-bot-token>") {{
    console.warn("Telegram bot token not configured");
    return;
  }}

  try {{
    await fetch(`https://api.telegram.org/bot${{botToken}}/sendMessage`, {{
      method: "POST",
      headers: {{ "Content-Type": "application/json" }},
      body: JSON.stringify({{
        chat_id: chatId,
        text,
        parse_mode: "Markdown",
      }}),
    }});
  }} catch (err) {{
    console.error("Failed to send Telegram message:", err);
  }}
}}

// GET endpoint for webhook verification (Telegram calls this to verify)
export const GET: APIRoute = async ({{ request, locals }}) => {{
  const url = new URL(request.url);
  const mode = url.searchParams.get("hub.mode");
  const challenge = url.searchParams.get("hub.challenge");
  const verifyToken = url.searchParams.get("hub.verify_token");

  const expectedToken = locals.runtime.env.TELEGRAM_WEBHOOK_VERIFY_TOKEN;

  if (mode === "subscribe" && verifyToken === expectedToken) {{
    return new Response(challenge, {{ status: 200 }});
  }}

  return new Response("Forbidden", {{ status: 403 }});
}};
"""

    return template.format(
        project_name=project_name,
        telegram_bot_token=telegram_bot_token,
    )


if __name__ == "__main__":
    print("Use via generate_wizard.py")