#!/usr/bin/env python3
"""
Faber Intent Wizard - Astro Project Setup

Creates package.json, astro.config.mjs, wrangler.toml, and CI/CD workflow.
"""

import json
from pathlib import Path
from typing import Any, Dict


def generate_package_json(config: Dict[str, Any]) -> str:
    """Generate package.json for the intent wizard project."""
    project_name = config["project_name"]

    pkg = {
        "name": project_name,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": {
            "dev": "astro dev",
            "build": "astro check && astro build",
            "preview": "astro preview",
            "deploy:staging": "wrangler pages deploy ./dist --branch=dev --project-name={project_name}-staging",
            "deploy:production": "wrangler pages deploy ./dist --branch=main --project-name={project_name}",
            "typecheck": "astro check",
            "lint": "eslint src --ext .ts,.tsx,.astro",
            "format": "prettier --write \"src/**/*.{ts,tsx,astro,json,css,md}\"",
            "db:generate": "drizzle-kit generate:sqlite",
            "db:migrate": "wrangler d1 migrations apply DB --remote",
            "db:studio": "wrangler d1 execute DB --remote --command '.schema'",
            "test": "vitest run",
        },
        "dependencies": {
            "astro": "^4.5.0",
            "@astrojs/cloudflare": "^10.0.0",
            "@astrojs/tailwind": "^5.1.0",
            "hono": "^4.0.0",
            "drizzle-orm": "^0.30.0",
            "zod": "^3.22.0",
            "@cloudflare/kv-asset-handler": "^0.3.0",
        },
        "devDependencies": {
            "@cloudflare/workers-types": "^4.2024000.0",
            "@types/node": "^20.0.0",
            "drizzle-kit": "^0.20.0",
            "typescript": "^5.4.0",
            "vitest": "^1.4.0",
            "wrangler": "^3.30.0",
            "eslint": "^8.56.0",
            "@typescript-eslint/eslint-plugin": "^7.0.0",
            "@typescript-eslint/parser": "^7.0.0",
            "prettier": "^3.2.0",
            "prettier-plugin-astro": "^0.13.0",
            "tailwindcss": "^3.4.0",
            "autoprefixer": "^10.4.0",
        },
        "engines": {
            "node": ">=18.14.1"
        },
        "packageManager": "npm@10.0.0"
    }

    return json.dumps(pkg, indent=2)


def generate_astro_config(config: Dict[str, Any]) -> str:
    """Generate astro.config.mjs with Cloudflare adapter and Tailwind."""
    project_name = config["project_name"]
    production_domain = config["deploy_targets"]["production"]["domain"]
    staging_domain = config["deploy_targets"]["staging"]["domain"]

    return f"""// astro.config.mjs - Generated by faber-intent-wizard for {project_name}

import {{ defineConfig }} from "astro/config";
import cloudflare from "@astrojs/cloudflare";
import tailwind from "@astrojs/tailwind";

export default defineConfig({{
  site: "https://{production_domain}",
  adapter: cloudflare({{
    platformProxy: {{
      enabled: true,
      persist: "./.wrangler/state",
    }},
  }}),
  integrations: [
    tailwind({{
      applyBaseStyles: true,
      configFile: "./tailwind.config.mjs",
    }}),
  ],
  output: "static",
  // Static output for Cloudflare Pages
  build: {{
    inlineStylesheets: "auto",
  }},
  // Vite config for D1/types
  vite: {{
    ssr: {{
      external: ["drizzle-orm"],
    }},
    optimizeDeps: {{
      exclude: ["drizzle-orm"],
    }},
  }},
  // Trailing slash for consistency
  trailingSlash: "always",
  // Compress HTML
  compressHTML: true,
  // Prefetch for better UX
  prefetch: true,
}});
"""


def generate_tailwind_config(config: Dict[str, Any]) -> str:
    """Generate tailwind.config.mjs with design system tokens."""
    fixture = config.get("fixture", "faber-brand")

    return f"""/** @type {{import('tailwindcss').Config}} */
export default {{
  content: [
    "./src/**/*.{{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}}",
  ],
  darkMode: "media",
  theme: {{
    extend: {{
      colors: {{
        // Faber design tokens - these map to CSS custom properties from design-tokens.css
        faber: {{
          primary: "var(--faber-primary)",
          "primary-dark": "var(--faber-primary-dark)",
          "primary-light": "var(--faber-primary-light)",
          secondary: "var(--faber-secondary)",
          accent: "var(--faber-accent)",
          success: "var(--faber-success)",
          warning: "var(--faber-warning)",
          danger: "var(--faber-danger)",
          info: "var(--faber-info)",
          background: "var(--faber-background)",
          surface: "var(--faber-surface)",
          "surface-hover": "var(--faber-surface-hover)",
          border: "var(--faber-border)",
          "border-focus": "var(--faber-border-focus)",
          text: "var(--faber-text)",
          "text-muted": "var(--faber-text-muted)",
          "text-light": "var(--faber-text-light)",
          "text-inverse": "var(--faber-text-inverse)",
        }},
      }},
      backgroundImage: {{
        "faber-primary": "var(--faber-gradient-primary)",
        "faber-hero": "var(--faber-gradient-hero)",
        "faber-card": "var(--faber-gradient-card)",
        "faber-stats": "var(--faber-gradient-stats)",
      }},
      fontFamily: {{
        sans: ["var(--faber-font-sans)"],
        mono: ["var(--faber-font-mono)"],
      }},
      spacing: {{
        xs: "var(--faber-space-xs)",
        sm: "var(--faber-space-sm)",
        md: "var(--faber-space-md)",
        lg: "var(--faber-space-lg)",
        xl: "var(--faber-space-xl)",
        "2xl": "var(--faber-space-2xl)",
        "3xl": "var(--faber-space-3xl)",
      }},
      borderRadius: {{
        sm: "var(--faber-radius-sm)",
        md: "var(--faber-radius-md)",
        lg: "var(--faber-radius-lg)",
        xl: "var(--faber-radius-xl)",
        "2xl": "var(--faber-radius-2xl)",
        full: "var(--faber-radius-full)",
      }},
      boxShadow: {{
        sm: "var(--faber-shadow-sm)",
        md: "var(--faber-shadow-md)",
        lg: "var(--faber-shadow-lg)",
        xl: "var(--faber-shadow-xl)",
      }},
      transitionDuration: {{
        fast: "var(--faber-transition-fast)",
        normal: "var(--faber-transition-normal)",
        slow: "var(--faber-transition-slow)",
      }},
      zIndex: {{
        dropdown: "var(--faber-z-dropdown)",
        sticky: "var(--faber-z-sticky)",
        fixed: "var(--faber-z-fixed)",
        "modal-backdrop": "var(--faber-z-modal-backdrop)",
        modal: "var(--faber-z-modal)",
        popover: "var(--faber-z-popover)",
        tooltip: "var(--faber-z-tooltip)",
      }},
    }},
  }},
  plugins: [],
}};
"""


def generate_wrangler_toml(config: Dict[str, Any]) -> str:
    """Generate wrangler.toml for Cloudflare Pages + Worker."""
    project_name = config["project_name"]
    production_domain = config["deploy_targets"]["production"]["domain"]
    staging_domain = config["deploy_targets"]["staging"]["domain"]
    d1_name = f"{project_name}-db"
    telegram_bot_token = config.get("telegram", {}).get("bot_token", "<your-telegram-bot-token>")
    telegram_chat_id = config.get("telegram", {}).get("chat_id", "<your-telegram-chat-id>")

    return f"""name = "{project_name}"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
[build]
command = "npm run build"
watch_dir = "src"
output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "{d1_name}"
database_id = "<your-d1-database-id>"

# KV namespace for sessions/cache
[[kv_namespaces]]
binding = "SESSIONS"
id = "<your-kv-namespace-id>"
preview_id = "<your-preview-kv-namespace-id>"

# Environment variables
[vars]
ENVIRONMENT = "production"
TELEGRAM_BOT_TOKEN = "{telegram_bot_token}"
TELEGRAM_CHAT_ID = "{telegram_chat_id}"
TELEGRAM_WEBHOOK_SECRET = "<your-webhook-secret>"
TELEGRAM_WEBHOOK_VERIFY_TOKEN = "<your-verify-token>"
CF_ACCESS_TEAM_DOMAIN = "<your-team>.cloudflareaccess.com"
CF_ACCESS_AUD = "<your-audience>"

# Production domain: {production_domain}
# Staging domain: {staging_domain}

[dev]
port = 8787
ip = "127.0.0.1"

# Staging environment
[env.staging]
name = "{project_name}-staging"
[vars]
ENVIRONMENT = "staging"

# Preview environment
[env.preview]
name = "{project_name}-preview"
[vars]
ENVIRONMENT = "preview"
"""


def generate_ci_workflow(config: Dict[str, Any]) -> str:
    """Generate GitHub Actions CI/CD workflow."""
    project_name = config["project_name"]
    production_domain = config["deploy_targets"]["production"]["domain"]
    staging_domain = config["deploy_targets"]["staging"]["domain"]

    return f"""name: CI/CD - {project_name}

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

env:
  NODE_VERSION: "20"
  PROJECT_NAME: {project_name}

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{{{ env.NODE_VERSION }}}}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run typecheck
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
        env:
          TELEGRAM_BOT_TOKEN: ${{{{ secrets.TELEGRAM_BOT_TOKEN }}}}
          TELEGRAM_CHAT_ID: ${{{{ secrets.TELEGRAM_CHAT_ID }}}}

  deploy-preview:
    name: Deploy Preview
    needs: lint-and-test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{{{ steps.deploy.outputs.url }}}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{{{ env.NODE_VERSION }}}}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          TELEGRAM_BOT_TOKEN: ${{{{ secrets.TELEGRAM_BOT_TOKEN }}}}
          TELEGRAM_CHAT_ID: ${{{{ secrets.TELEGRAM_CHAT_ID }}}}

      - name: Deploy to Cloudflare Pages (Preview)
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
          accountId: ${{{{ secrets.CLOUDFLARE_ACCOUNT_ID }}}}
          projectName: {project_name}-preview
          directory: ./dist
          branch: preview
          gitHubToken: ${{{{ secrets.GITHUB_TOKEN }}}}
        env:
          CLOUDFLARE_API_TOKEN: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
          CLOUDFLARE_ACCOUNT_ID: ${{{{ secrets.CLOUDFLARE_ACCOUNT_ID }}}}

  deploy-staging:
    name: Deploy Staging
    needs: lint-and-test
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://{staging_domain}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{{{ env.NODE_VERSION }}}}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          TELEGRAM_BOT_TOKEN: ${{{{ secrets.TELEGRAM_BOT_TOKEN }}}}
          TELEGRAM_CHAT_ID: ${{{{ secrets.TELEGRAM_CHAT_ID }}}}

      - name: Deploy to Cloudflare Pages (Staging)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
          accountId: ${{{{ secrets.CLOUDFLARE_ACCOUNT_ID }}}}
          projectName: {project_name}-staging
          directory: ./dist
          branch: dev
        env:
          CLOUDFLARE_API_TOKEN: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
          CLOUDFLARE_ACCOUNT_ID: ${{{{ secrets.CLOUDFLARE_ACCOUNT_ID }}}}

      - name: Notify Telegram (Staging Deploy)
        if: success()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d '{{
              "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
              "text": "🚀 *Staging Deployed*\\n{project_name} staging is live at https://{staging_domain}",
              "parse_mode": "Markdown"
            }}'

  deploy-production:
    name: Deploy Production
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://{production_domain}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{{{ env.NODE_VERSION }}}}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          TELEGRAM_BOT_TOKEN: ${{{{ secrets.TELEGRAM_BOT_TOKEN }}}}
          TELEGRAM_CHAT_ID: ${{{{ secrets.TELEGRAM_CHAT_ID }}}}

      - name: Deploy to Cloudflare Pages (Production)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
          accountId: ${{{{ secrets.CLOUDFLARE_ACCOUNT_ID }}}}
          projectName: {project_name}
          directory: ./dist
          branch: main
        env:
          CLOUDFLARE_API_TOKEN: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
          CLOUDFLARE_ACCOUNT_ID: ${{{{ secrets.CLOUDFLARE_ACCOUNT_ID }}}}

      - name: Notify Telegram (Production Deploy)
        if: success()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d '{{
              "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
              "text": "✅ *Production Deployed*\\n{project_name} is live at https://{production_domain}",
              "parse_mode": "Markdown"
            }}'

  # D1 migrations on production deploy
  db-migrate-production:
    name: Run D1 Migrations (Production)
    needs: deploy-production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{{{ env.NODE_VERSION }}}}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run D1 migrations
        run: npx wrangler d1 migrations apply DB --remote --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
          CLOUDFLARE_ACCOUNT_ID: ${{{{ secrets.CLOUDFLARE_ACCOUNT_ID }} }}

  # D1 migrations on staging deploy
  db-migrate-staging:
    name: Run D1 Migrations (Staging)
    needs: deploy-staging
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{{{ env.NODE_VERSION }}}}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run D1 migrations
        run: npx wrangler d1 migrations apply DB --remote --env staging
        env:
          CLOUDFLARE_API_TOKEN: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
          CLOUDFLARE_ACCOUNT_ID: ${{{{ secrets.CLOUDFLARE_ACCOUNT_ID }} }}
"""


def generate_drizzle_config(config: Dict[str, Any]) -> str:
    """Generate drizzle.config.ts for D1."""
    project_name = config["project_name"]

    return f"""import {{ defineConfig }} from "drizzle-kit";

export default defineConfig({{
  schema: "./src/db/schema.ts",
  out: "./drizzle",
  dialect: "sqlite",
  driver: "d1-http",
  dbCredentials: {{
    url: process.env.DATABASE_URL || "file:./local.db",
  }},
  verbose: true,
  strict: true,
}});
"""


def generate_db_schema_ts(config: Dict[str, Any]) -> str:
    """Generate TypeScript schema for Drizzle ORM."""
    return """// src/db/schema.ts - Drizzle ORM schema for intents table
// Generated by faber-intent-wizard

import { integer, sqliteTable, text, index, uniqueIndex } from "drizzle-orm/sqlite-core";

export const intents = sqliteTable(
  "intents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    clientContext: text("client_context").notNull(),
    productionContext: text("production_context").notNull().default("normal"),
    specMd: text("spec_md"),
    trajectoryMd: text("trajectory_md"),
    scopeBaselineMd: text("scope_baseline_md"),
    status: text("status").notNull().default("submitted"),
    extractedFacts: text("extracted_facts"), // JSON
    elicitedGaps: text("elicited_gaps"), // JSON
    backlogDraftMd: text("backlog_draft_md"),
    telegramNotified: integer("telegram_notified").notNull().default(0),
    telegramMessageId: integer("telegram_message_id"),
    createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
    updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP"),
  },
  (table) => ({
    statusIdx: index("idx_intents_status").on(table.status),
    createdAtIdx: index("idx_intents_created_at").on(table.createdAt),
    productionContextIdx: index("idx_intents_production_context").on(table.productionContext),
    telegramNotifiedIdx: index("idx_intents_telegram_notified").on(table.telegramNotified),
  })
);

export type Intent = typeof intents.$inferSelect;
export type NewIntent = typeof intents.$inferInsert;
"""


def generate_types_ts(config: Dict[str, Any]) -> str:
    """Generate TypeScript types for the project."""
    return """// src/types.ts - TypeScript types for Faber Intent Wizard
// Generated by faber-intent-wizard

import type { D1Database, KVNamespace } from "@cloudflare/workers-types";

export interface Env {
  DB: D1Database;
  SESSIONS: KVNamespace;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_CHAT_ID: string;
  TELEGRAM_WEBHOOK_SECRET: string;
  TELEGRAM_WEBHOOK_VERIFY_TOKEN: string;
  CF_ACCESS_TEAM_DOMAIN: string;
  CF_ACCESS_AUD: string;
  ENVIRONMENT: "production" | "staging" | "preview" | "development";
}

export interface IntentFormData {
  goal: string;
  audience: string;
  non_goals: string;
  ia: string;
  content_model: string;
  constraints: string;
  metrics: string;
  production_context: "prototype" | "normal" | "client-production";
}

export interface IntentArtifacts {
  specMd: string;
  trajectoryMd: string;
  scopeBaselineMd: string;
  backlogDraftMd: string;
  extractedFacts: Record<string, string>;
  elicitedGaps: string[];
}

export interface TelegramPayload {
  chat_id: string;
  text: string;
  parse_mode: "Markdown" | "HTML";
}
"""


def generate_base_layout(config: Dict[str, Any]) -> str:
    """Generate BaseLayout.astro."""
    project_name = config["project_name"]
    production_domain = config["deploy_targets"]["production"]["domain"]

    template = """---
// BaseLayout.astro - Generated by faber-intent-wizard for {project_name}

interface Props {{
  title: string
  description?: string
  canonicalURL?: string
}}

const {{ title, description, canonicalURL }} = Astro.props;
const siteUrl = "https://{production_domain}";
const pageUrl = canonicalURL || Astro.url.pathname;
---

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="generator" content={{Astro.generator}} />
    <title>{{title}}</title>
    <meta name="description" content={{description}} />
    <link rel="canonical" href={{pageUrl}} />
    <meta property="og:site_name" content="Faber Intent Wizard" />
    <meta property="og:title" content={{title}} />
    <meta property="og:description" content={{description}} />
    <meta property="og:url" content={{pageUrl}} />
    <meta property="og:type" content="website" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content={{title}} />
    <meta name="twitter:description" content={{description}} />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
    <script is:inline>
      // Dark mode detection
      if (localStorage.getItem("theme") === "dark" || (!localStorage.getItem("theme") && window.matchMedia("(prefers-color-scheme: dark)").matches)) {{
        document.documentElement.classList.add("dark");
      }}
    </script>
  </head>
  <body class="bg-faber-background text-faber-text antialiased font-sans dark:bg-faber-background dark:text-faber-text">
    <slot />
  </body>
</html>
"""
    return template.format(project_name=project_name, production_domain=production_domain)


def setup_astro_project(config: Dict[str, Any], output_dir: Path) -> None:
    """Set up the complete Astro project structure."""
    project_name = config["project_name"]

    # Create directory structure
    dirs = [
        "src/pages",
        "src/pages/api",
        "src/pages/intent",
        "src/components/wizard",
        "src/components/ui",
        "src/layouts",
        "src/styles",
        "src/db",
        "src/db/migrations",
        "public",
        "scripts",
        ".github/workflows",
    ]

    for d in dirs:
        (output_dir / d).mkdir(parents=True, exist_ok=True)

    # Write core files
    (output_dir / "package.json").write_text(generate_package_json(config))
    (output_dir / "astro.config.mjs").write_text(generate_astro_config(config))
    (output_dir / "tailwind.config.mjs").write_text(generate_tailwind_config(config))
    (output_dir / "wrangler.toml").write_text(generate_wrangler_toml(config))
    (output_dir / "drizzle.config.ts").write_text(generate_drizzle_config(config))
    (output_dir / "src" / "db" / "schema.ts").write_text(generate_db_schema_ts(config))
    (output_dir / "src" / "types.ts").write_text(generate_types_ts(config))
    (output_dir / "src" / "layouts" / "BaseLayout.astro").write_text(generate_base_layout(config))
    (output_dir / ".github" / "workflows" / "deploy.yml").write_text(generate_ci_workflow(config))

    # Create minimal global.css that imports design tokens
    global_css = """@import "./design-tokens.css";

/* Global styles */
* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  min-height: 100vh;
}

/* Focus visible for accessibility */
:focus-visible {
  outline: 2px solid var(--faber-primary);
  outline-offset: 2px;
}

/* Selection styles */
::selection {
  background-color: var(--faber-primary);
  color: white;
}

/* Scrollbar styles */
::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

::-webkit-scrollbar-track {
  background: var(--faber-surface);
}

::-webkit-scrollbar-thumb {
  background: var(--faber-border);
  border-radius: 4px;
}

::-webkit-scrollbar-thumb:hover {
  background: var(--faber-text-muted);
}
"""
    (output_dir / "src" / "styles" / "global.css").write_text(global_css)

    # Create postcss.config.cjs
    postcss_config = """module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
"""
    (output_dir / "postcss.config.cjs").write_text(postcss_config)

    # Create tsconfig.json
    tsconfig = {
        "extends": "astro/tsconfigs/strict",
        "compilerOptions": {
            "strictNullChecks": True,
            "baseUrl": ".",
            "paths": {
                "@/*": ["src/*"]
            },
            "types": ["astro/client", "@cloudflare/workers-types"]
        },
        "include": ["src/**/*", "astro.config.mjs", "tailwind.config.mjs", "drizzle.config.ts"],
        "exclude": ["node_modules", "dist", ".wrangler"]
    }
    (output_dir / "tsconfig.json").write_text(json.dumps(tsconfig, indent=2))

    # Create .gitignore
    gitignore = """# Dependencies
node_modules/

# Build outputs
dist/
.wrangler/

# Environment files
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*

# Testing
coverage/

# Drizzle
drizzle/

# Turbo
.turbo/
"""
    (output_dir / ".gitignore").write_text(gitignore)

    # Create README.md
    readme = f"""# {project_name}

Faber Intent Wizard — Public `/intent` route for structured project intake.

## Features

- **Multi-step wizard** — 7 steps of structured elicitation (goal, audience, non-goals, IA, content model, constraints, metrics)
- **Deterministic artifacts** — Generates spec.md, trajectory.md, scope-baseline.md using Faber's intent-collect logic
- **D1 persistence** — Stores submissions with full artifact history
- **Telegram notifications** — Real-time alerts on new submissions
- **Backlog draft generation** — GitHub issue-ready markdown from submitted intents
- **Design system integration** — Uses Faber design tokens ({config.get("fixture", "faber-brand")} fixture)

## Quick Start

```bash
# Install dependencies
npm install

# Configure environment
cp .env.example .env
# Edit .env with your credentials

# Run development server
npm run dev

# Build for production
npm run build

# Deploy to staging (dev branch)
npm run deploy:staging

# Deploy to production (main branch)
npm run deploy:production
```

## Environment Variables

| Variable | Description | Required |
|----------|-------------|----------|
| `TELEGRAM_BOT_TOKEN` | Telegram bot token for notifications | Yes |
| `TELEGRAM_CHAT_ID` | Telegram chat ID for notifications | Yes |
| `TELEGRAM_WEBHOOK_SECRET` | Secret for webhook verification | Yes |
| `TELEGRAM_WEBHOOK_VERIFY_TOKEN` | Token for webhook verification | Yes |
| `CLOUDFLARE_API_TOKEN` | Cloudflare API token for deployments | Yes (CI) |
| `CLOUDFLARE_ACCOUNT_ID` | Cloudflare account ID | Yes (CI) |

## Project Structure

```
src/
├── pages/
│   ├── index.astro          # Landing page
│   ├── intent.astro         # Multi-step wizard
│   ├── intent/
│   │   └── success.astro    # Confirmation page
│   └── api/
│       ├── intent.ts        # POST /api/intent endpoint
│       └── telegram.ts      # Telegram webhook handler
├── components/
│   ├── wizard/              # Wizard step components
│   └── ui/                  # Reusable UI components
├── layouts/
│   └── BaseLayout.astro     # Base HTML layout
├── styles/
│   ├── global.css           # Global styles + design tokens import
│   └── design-tokens.css    # Generated design tokens (from faber-design-system)
├── db/
│   ├── schema.ts            # Drizzle ORM schema
│   ├── schema.sql           # Raw D1 SQL schema
│   └── migrations/          # D1 migrations
├── types.ts                 # TypeScript types
├── env.d.ts                 # Env types
└── middleware.ts            # Astro middleware (if needed)
```

## Deploy Targets (per FRAMEWORK.md §13)

- **Production**: {config["deploy_targets"]["production"]["domain"]} (main branch)
- **Staging**: {config["deploy_targets"]["staging"]["domain"]} (dev branch)
- **Preview**: Ephemeral PR deployments (continue-on-error: true)

## Telegram Bot Commands

Once deployed, the bot responds to:
- `/start` / `/help` — Show help
- `/list` — List recent intents
- `/status <id>` — Check intent status
- `/summary <id>` — Show scope baseline

## License

MIT — Generated by Faber Intent Wizard skill.
"""
    (output_dir / "README.md").write_text(readme)

    # Create .env.example
    env_example = """# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN=your-bot-token-here
TELEGRAM_CHAT_ID=your-chat-id-here
TELEGRAM_WEBHOOK_SECRET=your-webhook-secret-here
TELEGRAM_WEBHOOK_VERIFY_TOKEN=your-verify-token-here

# Cloudflare (for CI/CD - set as GitHub secrets)
# CLOUDFLARE_API_TOKEN=
# CLOUDFLARE_ACCOUNT_ID=

# Local development (optional)
# DATABASE_URL=file:./local.db
"""
    (output_dir / ".env.example").write_text(env_example)

    print(f"  ✓ Astro project structure created at {output_dir}")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Set up Astro project structure")
    parser.add_argument("--project-name", required=True, help="Project name")
    parser.add_argument("--output-dir", required=True, help="Output directory")
    parser.add_argument("--production-domain", required=True, help="Production domain")
    parser.add_argument("--staging-domain", required=True, help="Staging domain")
    parser.add_argument("--fixture", default="faber-brand", help="Design system fixture")

    args = parser.parse_args()

    config = {
        "project_name": args.project_name,
        "deploy_targets": {
            "production": {"domain": args.production_domain, "branch": "main"},
            "staging": {"domain": args.staging_domain, "branch": "dev"},
        },
        "fixture": args.fixture,
    }

    setup_astro_project(config, Path(args.output_dir))